### ISSUE TITLE
Exception filtering tests: No tests matched the  filter because it contains one or more properties that are not valid (Name). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again.

### ISSUE THREAD

**Issue by francisco-ltech** [formulahendry/vscode-dotnet-test-explorer#1]
Getting this error message when using the extension, tests run fine from Visual Studio and Command Line using dotnet test.

Using xunit 2.2.0

Snippet of test class:

```
[Collection("UserIsNotRegisteredBadData")]
public class UserIsNotRegisteredBadData
{
        [Fact]
        public async Task ReturnsErrorForBadEmail()
        {
            await MakeRequest(stringData);
            AssertResult();
        }
}
```

**Comment by formulahendry** [comment]
Could you please share the whole screenshot of terminal?

**Comment by francisco-ltech** [comment]
It seems it has to do with the --filter flag, as running all test in project runs ok with dotnet test but running individual tests with the --filter flag is spitting out this message

![image](https://user-images.githubusercontent.com/29372459/29265938-ceda185e-80da-11e7-85d3-4e8df387dab0.png)

**Comment by formulahendry** [comment]
@francisco-ltech , this issue has been fixed, please try the latest version.

**Comment by francisco-ltech** [comment]
Thank you!
