### ISSUE TITLE
Error when discovering tests in project with large number of tests

### ISSUE THREAD

**Issue by NoXHealeR** [formulahendry/vscode-dotnet-test-explorer#105]
When trying to discover tests in project with large number of tests (~2500) i am getting **stdout maxBuffer exceeded** error. However, after deleting 500-600 tests from project, there is no error showed and tests are found
![error](https://user-images.githubusercontent.com/41321057/42802588-70cac9be-89b4-11e8-8cbe-c95996ddbf06.JPG)

**Comment by nikitaigudinroko** [comment]
Possible fix - set bigger **maxBuffer** setting in executor.js:
![fix](https://user-images.githubusercontent.com/41358670/42864085-467efdb6-8a76-11e8-8c3e-8b93d3f41fe2.JPG)

**Comment by stefanforsberg** [comment]
Thanks for reporting and suggesting a fix =)
