### ISSUE TITLE
Frequent VS Code and dotnet process restarts

### ISSUE THREAD

**Issue by turowicz** [formulahendry/vscode-dotnet-test-explorer#106]
Hi

First I would like to say what a great project you've made. It is incredibly useful!

The problem I'd like to report is that after debugging a test I am frequently forced to close the VS Code and kill all dotnet processes. 50 times a day minimum.

I'm not sure what is causing this, but the issue manifests itself by:

- Intelisense breaking completely
- Not being to able to start the debugger session
- System.InvalidOperationException: Debug session already started
- Freezing on "Debugging method 'MyMethod'..."

And more... they are all caused mostly by cancelling test debug session or when exceptions are thrown during the test.

**Comment by stefanforsberg** [comment]
Hi,
the debug options added to code lens are not provided by this extension but by [omnisharp](https://github.com/OmniSharp/omnisharp-vscode)
