### ISSUE TITLE
No Discover explorer for NUnit

### ISSUE THREAD

**Issue by lorranpalmeira** [formulahendry/vscode-dotnet-test-explorer#107]
When is used NUnit test-explorer no discover the tests.

![image](https://user-images.githubusercontent.com/18705060/42900518-81a44814-8a9f-11e8-85b9-fb48795edef1.png)
But my tests are executed

![image](https://user-images.githubusercontent.com/18705060/42900736-fd175ba8-8a9f-11e8-87d0-4f58988bf962.png)

**Comment by gustavobigardi** [comment]
same here.

**Comment by stefanforsberg** [comment]
Hello, have you looked at the known issues in the readme? If you have and you're still having problem it would be helpful to known dotnet sdk version (dotnet --version) and what is written in the output / test explorer terminal window.

**Comment by gustavobigardi** [comment]
I searched for issues like this one, and for me, it's the language, since dotnet cli is using pt-br.
I will remove other languange packs than english from my dotnet core setup path, but is there any prediction or intention to fix it to work with other languages?

**Comment by olegon** [comment]
Thanks, @gustavobigardi ! Your tip was very useful. I've changed the language and it's working right now!

I've included a environment variable `DOTNET_CLI_UI_LANGUAGE=en` (changing dotnet cli language) and I've removed the directory `<SDK_HOME>/<VERSION>/pt-BR` (changing dotnet-test language output).

**Comment by lorranpalmeira** [comment]
It´s not necessary setup "DOTNET_CLI_UI_LANGUAGE=en" just remove folder pt-BR from SDK folder.

C:\Program Files\dotnet\sdk\2.1.301

Thank you guys.

**Comment by olegon** [comment]
Thanks, @lorranpalmeira !
