### ISSUE TITLE
testArguments setting doesn't get applied

### ISSUE THREAD

**Issue by jazzmanflynn** [formulahendry/vscode-dotnet-test-explorer#113]
I don't think the testArguements setting is working.
"dotnet-test-explorer.testArguments": "-a ../packages/NUnit3TestAdapter.3.10.0"
-->
Executing dotnet test -t -v=q in c:\XXXXXXXXXXXX

**Comment by stefanforsberg** [comment]
Hmm, yea, the testArguments are only applied when running dotnet test, not the discovery phase (dotnet test -t). It's fixed in master so it should be included in the next release.
