### ISSUE TITLE
Status color of tests 

### ISSUE THREAD

**Issue by martinus-e** [formulahendry/vscode-dotnet-test-explorer#116]
I really like dotnet-test explorer. 

However, when running VSCode in a light color theme (there are still people that prefer light above the dark themes) the status colors for the tests are hardly visible.. It would be nice if this is configurable or at least better visible in a light theme!

![test-colors](https://user-images.githubusercontent.com/42490434/44297831-93234d00-a2d8-11e8-8ff2-21c9ed3a795f.png)

**Comment by stefanforsberg** [comment]
Ah yes, thanks for your report. Due to the fact that vscode does not let us access if the user runs a dark or light color theme programmatically we'll have to add a color theme setting.

**Comment by stefanforsberg** [comment]
This better?

![image](https://user-images.githubusercontent.com/358570/44302141-7ceeae80-a323-11e8-93bc-f283eddfcb71.png)

![image](https://user-images.githubusercontent.com/358570/44302154-97288c80-a323-11e8-8d32-3d3dc6c7a485.png)

**Comment by stefanforsberg** [comment]
0.5.1 was just released and the icons should have better visibility. Take it for a spin and see how it feels.

**Comment by martinus-e** [comment]
Just tested it, it is a great improvement! Looks very nice now!

**Comment by lonix1** [comment]
Is there a way to set the skip/yellow color or to change it to green?

With xUnit v3 alpha (or the [Xunit.SkippableFact](https://www.nuget.org/packages/Xunit.SkippableFact) package) it's possible to skip tests dynamically, e.g. by platform or some boolean condition:
````cs
Skip.If(someCondition);
````

So those should always be skipped, and so are always yellow. And that makes the test explorer all yellow, which gives the impression there are problems, but there aren't. If it's possible, I would disable the yellow color feature altogether (in that use case).
