### ISSUE TITLE
Make Test Explorer reload settings when the refresh button is pressed

### ISSUE THREAD

**Issue by tdwright** [formulahendry/vscode-dotnet-test-explorer#119]
Currently a restart of VS Code is required when changes are made to settings. Intuitively, it feels as though they should get reloaded when the refresh button is pressed.

This would allow, for example, tests to be discovered without restarting VS Code.

Failing this (or even just in the short term) perhaps it could just be made clearer that a restart is needed.

**Comment by stefanforsberg** [comment]
The extension should handle changes to testProjectPath in a better way now with 0.5.1

**Comment by tdwright** [comment]
Speedy turnaround. Can confirm this is now working for me. Thanks!
