### ISSUE TITLE
Test Result Icon Bug

### ISSUE THREAD

**Issue by Xenomega** [formulahendry/vscode-dotnet-test-explorer#121]
Hello,

I am currently overriding/extending the MSTest v2 framework. At one point, I extend TestMethodAttribute and I override it's Execute() function to modify how tests are invoked, such that I can run each test twice (in different contexts). Running one test returns 2 results, so I modify the "DisplayName" property located in the "Microsoft.VisualStudio.TestTools.UnitTesting.TestResult" instance to give them unique names.

In VS2017 Enterprise, I get two results for every test, and all tests succeed (green). In your extension however, it tells me the tests passed "Total tests: 2. Passed: 2. Failed: 0. Skipped: 0.", but the result icon (green check mark, red x, grey question mark) does not update from what it was before the test started. I  found out if I don't modify TestResult.DisplayName, your extension correctly sets the icon each time.

I am guessing you are setting the result icon by indexing tests somehow with display name, or similar. Obviously result icons shouldn't be indexed by the display name, as VS2017 Enterprise does not have this behavior. If you could address this issue, it would be greatly appreciated.

Thank you for your time, and keep up the good work.

**Comment by stefanforsberg** [comment]
Hello,
unfortunately the built in tooling around test discovery for DisplayName (and similar attributes for other test frameworks) are unpredictable at best. It would require some rethinking and probably a lot of rewriting of how the extension works which I currently do not have time for. But if you come up with a way to implement it we love pull requests =)

**Comment by stefanforsberg** [comment]
@Xenomega Hello, in a recent update we did some changes to test discovery and tests that are run but was not discovered are now added to the tree. I'm curious as to how this affects your scenario?
