### ISSUE TITLE
custom parameters cause display issues

### ISSUE THREAD

**Issue by steveoh** [formulahendry/vscode-dotnet-test-explorer#125]
I added coverlet args to my test command to get code coverage in a watch task. 

```json
{
    "dotnet-test-explorer.testArguments": "/p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../../lcov.info"
}
```

This causes the test window to display this under all the other tests. Not a huge issue but it should probably be ignored?

![image](https://user-images.githubusercontent.com/325813/44553253-1f26e180-a6ea-11e8-8e0b-bf94746eb348.png)

**Comment by stefanforsberg** [comment]
This should be fixed with 0.5.2
