### ISSUE TITLE
Allow users to cancel hanging tests

### ISSUE THREAD

**Issue by goblinfactory** [formulahendry/vscode-dotnet-test-explorer#132]
Feature request : Ability to cancel a hanging test that will not stop

```ruby
When I start a test
and the test hangs
and the test is accidentally using a lot of cpu and threatening to set my macbook pro on fire
When I click the stop icon
Then the test is stopped (or the spawned dotnet test process running the test is killed)
and I can put away the fire extinguisher
and peace reigns once more on earth
```
:)

I will be hugely in your debt if this feature can be provided!

**Comment by goblinfactory** [comment]
I posted this suggestion, after I asked on twitter if anyone knew if dotnet had a stop test command, and my mate @robertfriburg said, 

> "run "ps aux" in the terminal, identify the PID of the dotnet test process and then kill PID"

, and I thought, huh, it can't be that hard to kick off that as a macro or whatever it is that we as VSCode extension writers already do to actually start the test?

**Comment by antonblu** [comment]
did you try clicking the refresh icon at the top of the test explorer left panel ? the refresh will discover all the tests again and stops any test still running(the spinning icon will stop).

**Comment by stefanforsberg** [comment]
@antonblu That doesn't actually kill the process that's running the test I'm afraid, only refreshes the ui.

**Comment by goblinfactory** [comment]
... or put another way, we need a "stop" or "kill" button. If the button actually issues a `stop-process` command, then the button should be clearly marked visually as a kill button, because you risk losing data as the thread is removed of it's life, san's notice! 
If the stop button, were to send a polite `please stop when you have a moment` message to dotnet somehow, then a simple square stop is appropriate.
What do you guys think?

**Comment by goblinfactory** [comment]
@stefanforsberg where based? I see palm trees in your profile pic, so assuming you're not UK based? on the off chance you're in London, I'd be happy to meet up at lunch time and see if we can hack something together around the test runners, and-or take a look at the test runner open source stuff to see if they have or would want some signalling?

**Comment by stefanforsberg** [comment]
@goblinfactory I have not found a way to signal to the test framework that it should stop what it's doing and then run all necessary cleanups. What we might be able to do is the more brute force approach of simply killing all threads (or shoot the test runner in the back as it were). 

If we add that, what would the extension do after killing current test run? Perform a discover again?

**Comment by stefanforsberg** [comment]
Hey, we've added "stop started test processes" with 0.5.5 (https://github.com/formulahendry/vscode-dotnet-test-explorer#new-in-055). It was non-trivial to implement so please try it and give feedback =)
