### ISSUE TITLE
Name the process that is spawned when dotnet test runs after the test being run

### ISSUE THREAD

**Issue by goblinfactory** [formulahendry/vscode-dotnet-test-explorer#133]
Feature : **Name the process that is spawned when dotnet test runs after the test being run**
so that I can easily use powershell or bash to stop hanging tests 
because I will be able to find "grep" processes with name starting with 'dotnettest-'

```ruby
Given a unit test named {testname}
when I click the triangle to start the test
then the spawned process will be named 'dotnettest-{testname}'
``` 

**Rationale**
I'm not familiar with the process of spawning dotnet test commands, so not even sure if this is viable. I'm putting here because I started writing a cross platform powershell script that would check for hanging dotnet test's, and kill them as part of my build's 'clean' step. If the processes were named in a very specific way then i would have less risk I accidentally kill the wrong process.

**Comment by goblinfactory** [comment]
**Some possibly helpful background info**
1. Run the following command in powershell to ensure that no dotnet processes are running<br/> `> get-process | where { $_.Name -like "dotnet*" }` (this works cross platform)
  - observe that no processes are running. (If something does come back, then shut down any IDE's that may have launches dotnet processes, or wait until running this returns no results)
2. start a reasonably long running unit test, or a mini integration test that writes a few files to disk and takes a few seconds.
3. while the unit test is running, run the same command again.
  - observe multiple dotnet ProcessName's, ideally we'd want that to be named `dotnet-test-{xxx}`
  - if we launch any special processes in order to monitor the test results, then we should name them in a way that allows us to identify the test and any test-system1 processes?  

For example; when I run a small test that does a bit of stuff, this is what I see:

<img width="600" alt="screen shot 2018-08-28 at 14 12 19" src="https://user-images.githubusercontent.com/1073487/44725086-689d7500-aacc-11e8-94de-8114b4fd0a3e.png">

It will be really helpful to know which process was my actual test, and which processes are houskeeping processes monitoring my test.

**Comment by stefanforsberg** [comment]
VSCode actually has it's own process explorer that you can reach from the Help / Open process explorer. This will only (I guess at least?) show processes spawned from vscode itself and the process the extension start should be under the extensionsHost and look something like this

![image](https://user-images.githubusercontent.com/358570/44769653-aac6c500-ab65-11e8-961f-59da570540da.png)

There you can also kill that process if needs be. This might be a good enough workaround for both this and #132?

**Comment by goblinfactory** [comment]
If I'm going to have to live with scripts on the command line, then I'm probably going simply kick off the tests manually myself. For this plugin to be truly useful, if you have a play button, then you need a stop button, I don't think there's any way we can avoid that?

For now, If it is at all possible to name the thread then that would make shutting down the tests really easy, e.g. a 1 liner ` get-process | where { $_.name like -'mytest-xxx' } | stop-process` . I'd have that script on speed dial, assign it a hot key macro in VSCode. i.e. I wouldn't need to eyeball the VSCode process explorer, because that's a manual slow process. Let's rather get the computer to do these repetitive error prone tasks! (grin)

To help with that, I believe we would need this specific feature request, if at all possible?
:)
If it's not possible for some reason, then it would be really helpful to know why, that way someone reading the comments might go, "hey, I know how we could actually do that!"

I didn't know about the process explore for VSCode, that is really helpful! Thank you for that!

**Comment by stefanforsberg** [comment]
I don't know of a way to name the processes to make your script work. However, what I guess you're really after is that the extension should have an easy way to kill all the processes started by it, the "stop button" if you will.

Previously we ran all the tests commands in the built in terminal which had the advantage of being able to do a ctrl-c to kill any process currently running in it. Running in an actual terminal has disadvantages though, the main one being that it will be hard to run commands in parallel. 

I'm sure there is a way to keep track of the commands we're executing and kill the process running them if the user wants us too. Did I mention that we love pull requests? =)
