### ISSUE TITLE
TestFixture parameters in Nunit seems to cause testexplorer to fail

### ISSUE THREAD

**Issue by Mgenuit** [formulahendry/vscode-dotnet-test-explorer#137]
TestFixture parameters in Nunit seems to cause testexplorer to fail.

I tried to add parameters to my test fixture in and it caused the testexplorer to display a “Containder[title].push is not a function” error.

Manually running the dotnet command does list all the expected testcases.

![2018-09-04_16-26-28](https://user-images.githubusercontent.com/42111466/45038953-b3863200-b062-11e8-98cd-9b25c92980f6.png)

**Comment by Mgenuit** [comment]
## Intro
OK.
So.
I have done some digging and I have found the function what causes my issue and a potential fix. The only thing I’m not sure of is if this will break anything (though my initial testing suggests it won’t).

I will do a short (turned out to be a quite lengthy one) writeup of what I found. If you (or any other contributors) are reasonably sure this won’t break things I will make a pull request.

## The other bug

Before I get in to the code I believe I found another related bug while trying to reproduce my original bug in the nunit test file that came with the repo.

__Given__ you have more than one classfile filled with tests,
__And__ both classes have at least one TestFixture,
```C#
[TestFixture]
public class Test1
```
__And__ one of the classes has multiple Test fixtures with a property.
```C#
[TestFixture(“propertyOne”)]
[TestFixture(“propertyTwo”)]
public class Test2
```

__When__ You press refresh.
__You expect__
![2018-09-06_16-29-14](https://user-images.githubusercontent.com/42111466/45164488-d47d8d00-b1f2-11e8-89e4-6c7a362f0840.png)

__But you Get__
![2018-09-06_16-32-47](https://user-images.githubusercontent.com/42111466/45164527-e6f7c680-b1f2-11e8-9b47-1343042f171b.png)
## The cause 

Something seems to happen in this part of the code

**File**=dotnetTestExplorer.ts
```TypeScript
this.discoveredTests.forEach((name: string) => {
            // this regex matches test names that include data in them - for e.g.
            //  Foo.Bar.BazTest(p1=10, p2="blah.bleh")
            const match = /([^\(]+)(.*)/g.exec(name);
            if (match && match.length > 1) {
                const parts = match[1].split(".");
                if (match.length > 2 && match[2].trim().length > 0) {
                    // append the data bit of the test to the test method name
                    // so we can distinguish one test from another in the explorer
                    // pane
                    const testMethodName = parts[parts.length - 1];
                    parts[parts.length - 1] = testMethodName + match[2];
                }
                this.addToObject(structuredTests, parts);
            }
        });


private addToObject(container: object, parts: string[]): void {
        const title = parts.splice(0, 1)[0];

        if (parts.length > 1) {
            if (!container[title]) {
                container[title] = {};
            }
            this.addToObject(container[title], parts);
        } else {
            if (!container[title]) {
                container[title] = [];
            }

            if (parts.length === 1) {
                container[title].push(parts[0]);
            }
        }
    }

```
The Regular expression matches in a way the rest of the code seems not to be able to handle correctly. _Really don’t know how to explain this better without unnecessarily lengthening this already lengthy post._

Changing the regular expression to:
```
([^]+)(.*)
```
Seems to solve both bugs and not create any more bugs. (that I could find by running all the tests that came with the repo). But I don’t know why the first capture group  had to exclude “(” in the first place.

The regular expression was added in commit 7635b26b9f55bb0f48479f019acda5fd048894bf by user @avranju. Perhaps you can tell me whether making this change will cause unintended side effects?

If not I will be making a pull request soon.

**Comment by stefanforsberg** [comment]
Sweet. The commit you talk about happened before I got involved with the project so I'm not totally sure as to the reasoning behind it. Looking at the comments surrounding it it seems to be related to test cases (we have some example if you start the xunit project in debug mode).

![image](https://user-images.githubusercontent.com/358570/45176087-45cb3900-b20f-11e8-98ca-fa58c814b420.png)

What you could do is create a pull request with the regexp change as well as add a test class with a TestFixture in the nunit test folder (./test/nunit). If you can verify that the tree loads ok and that you can run the tests in these different kind of test projects we have after the change that would be really appreciated.
