### ISSUE TITLE
Testcases with similar names get run together

### ISSUE THREAD

**Issue by Mgenuit** [formulahendry/vscode-dotnet-test-explorer#139]
## Intro
This bug was found to exist on the master branch as part of testing the fix of issue 137.
### Bug present on
* __Branch:__  Master
* __Last Commit__: f40b8073eb24d19349e82d1675b97b4b22755dc0
### Steps to preproduce
1. Open the NUnit test cases
2. Refresh test explorer so that all testcases are displayed
_Testclass2 should have a testcase ”Pass” and a testcase “Pass2”_
3. press the arrow on the right of testcase “Pass”
### Expected result
Testcase “Pass” should start running and showing a spinning circle.
### Experienced result
Testcase “Pass” and “Pass2” start running and showing a spinning circle.

**Comment by stefanforsberg** [comment]
Should be fixed with 0.5.4
