### ISSUE TITLE
The tests are not discovered in netcoreapp2.0 with xunit

### ISSUE THREAD

**Issue by diogojhony** [formulahendry/vscode-dotnet-test-explorer#14]

**Comment by formulahendry** [comment]
Have you opened the folder of test project? Any error message you see?

**Comment by diogojhony** [comment]
No error message is displayed. I did the test and if I open the folder of test project it working perfectly, however for work with DDD i have several projects in the same folder, i informed the "dotnet-test-explorer.testProjectPath" and the tests are not discovered.

**Comment by formulahendry** [comment]
What's the result when you run `dotnet test -t` in terminal?

**Comment by diogojhony** [comment]
With the command, was able to identify the error in one of the project classes (error CS0246: The name of the type or namespace" DataAttribute "can not be found), after making adjustments the test methods were found.

**Comment by formulahendry** [comment]
One follow-up question: Before you fix the error, the test explorer is empty or something like below?
![image](https://user-images.githubusercontent.com/1050213/29646874-8c3a8728-88b8-11e7-8419-6629abca4b35.png)

**Comment by diogojhony** [comment]
It was empty.

**Comment by formulahendry** [comment]
Got it. Thanks! I have created a separate issue #17 to improve this.
Closing this one.

**Comment by diogojhony** [comment]
Thanks!
