### ISSUE TITLE
The status in the code is not displayed

### ISSUE THREAD

**Issue by dayhi** [formulahendry/vscode-dotnet-test-explorer#148]
![image](https://user-images.githubusercontent.com/18325669/46155602-430db200-c2aa-11e8-8c5e-4caafa857fdd.png)
There is no green check mark in the pink box. Is this a bug?

**Comment by stefanforsberg** [comment]
Hmm, we don't add any code lens status to test _classes_, only to test methods. So there should be some indication as to how the test went in the blue "square" below

![image](https://user-images.githubusercontent.com/358570/46167376-ed2f0f00-c295-11e8-8d3d-06e6847c00d8.png)

**Comment by raaraya** [comment]
Same happening to me.

Modified User Settings:
```
    "dotnet-test-explorer.autoExpandTree": true,
    "dotnet-test-explorer.codeLensFailed": "Failed",
    "dotnet-test-explorer.codeLensPassed": "Passed",
    "dotnet-test-explorer.codeLensSkipped": "Skipped"
```

VSCode version: 

![image](https://user-images.githubusercontent.com/15349425/47609966-bb30da00-da06-11e8-8855-0add5ae874b7.png)

**Comment by stefanforsberg** [comment]
0.5.5 was just released, can you check if that solved the problem for you?
