### ISSUE TITLE
Feature: Go to test code

### ISSUE THREAD

**Issue by jdelrue** [formulahendry/vscode-dotnet-test-explorer#15]
Right click -> go to code of test

**Comment by dsarfati** [comment]
I like the idea of a double-click.

**Comment by janaka** [comment]
PR #35 (by pulling in PR #32 with minor enhancements) covers this.

**Comment by janaka** [comment]
@dsarfati hmm not sure how to catch double-clicks 😄 Will keep an eye out.

**Comment by janaka** [comment]
Confirmed this has been shipped.
