### ISSUE TITLE
Red cross / green tick missing from Code

### ISSUE THREAD

**Issue by garfbradaz** [formulahendry/vscode-dotnet-test-explorer#155]
Hey Guys,

The status markers seem to be missing in the latest update (Against the methods):

![image](https://user-images.githubusercontent.com/959766/47269913-03aa4c80-d55c-11e8-93a3-b977b65867d4.png)

My current code is running on _Windows 10 Enterprise 1809_ 👍 
Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Im running _0.5.4_ of the extension.

**Comment by stefanforsberg** [comment]
Thanks for reporting! I think this might be related to a change in omnisharp extension. Do you happen to know what version of that you are running?

**Comment by garfbradaz** [comment]
Hey @stefanforsberg 

Hope you are well fella?

Is this what you need:

> Path: C:\Users\gareth.bradley\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\OmniSharp.exe

**Comment by stefanforsberg** [comment]
Hey and thanks! There has been some changes as to how symbols are handled in vscode, this is likely the issue here as well as for #148. We'll try to fix it as soon as we can.

**Comment by garfbradaz** [comment]
Top marks @stefanforsberg. I'm not a TS guru, but if you detail where the issue and what it is here, I don't mind trying to pick it up later next week, if you are stuck for time. This is one of my VS Code extensions that helps me a load so happy to help anyway.

**Comment by stefanforsberg** [comment]
Ah thanks man! The (hopeful) fix will come in a few days ⚡️

**Comment by stefanforsberg** [comment]
0.5.5 was just released, can you check and see if that helps with this problem?

**Comment by garfbradaz** [comment]
Boom fixed:

![image](https://user-images.githubusercontent.com/959766/47963956-0f514500-e02b-11e8-8de7-28c39a1991a4.png)


Smashed it out of the park @stefanforsberg
