### ISSUE TITLE
Tests duplicated

### ISSUE THREAD

**Issue by Goliardo** [formulahendry/vscode-dotnet-test-explorer#159]
Issue Type: <b>Bug</b>

For a .NET proyect, when tests are listed they displayed as duplicated. If I play a test it executes twice

Extension version: 0.5.4
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

<details>
<summary>Image</summary>
[image](https://user-images.githubusercontent.com/4850020/47637506-2e983000-db5c-11e8-8025-133780c0dbc8.png)
</details>

**Comment by janaka** [comment]
@Goliardo are you able to share a git repo that reproduces the issue?

**Comment by Recodify** [comment]
Seeing something similar:

![image](https://user-images.githubusercontent.com/5644228/54023992-547ab480-418e-11e9-847e-100272dbba71.png)

**Comment by MatthewS2077** [comment]
I have the same problem. Started happening today after updating to 0.6.5
![1](https://user-images.githubusercontent.com/24437047/54542559-1d0ed200-49f0-11e9-992e-b0282adb3ced.png)
![2](https://user-images.githubusercontent.com/24437047/54542598-30ba3880-49f0-11e9-8f9f-426e7120006f.png)

**Comment by stefanforsberg** [comment]
Hmm, interesting. What version of the dotnet sdk are you using and what version of the nuget testadapter and your unit test framework are you using?

**Comment by MatthewS2077** [comment]
dotnet core 2.2.103
xunit 2.4.1
xunit.runner.visualstudio 2.4.1

**Comment by stefanforsberg** [comment]
Thanks, I have not been able to reproduce this error I'm afraid. If you can create a very basic project which causes this error for you it would be much appreciated.

**Comment by MatthewS2077** [comment]
The issue seems to be with [Fact].  [Theory] works as expected.

So with the code below... if I comment out [Fact] then it works as expected. 

`[Fact]
        void Test1()
        {
            Assert.True(false);
        }`


`[Theory]
        [InlineData()]
        void Test2()
        {
            Assert.True(false);
        }`

**Comment by MatthewS2077** [comment]
> Thanks, I have not been able to reproduce this error I'm afraid. If you can create a very basic project which causes this error for you it would be much appreciated.

Project is attached in this zip.

[Test1.zip](https://github.com/formulahendry/vscode-dotnet-test-explorer/files/2998548/Test1.zip)

**Comment by MatthewS2077** [comment]
Changing all my `[Fact]` to `[Theory][InlineData()]` is a workaround, but not ideal. Can fix the [Fact] issue?

**Comment by stefanforsberg** [comment]
@MatthewS2077 I'm using [Fact] in all my own test project which works as expected so it does not seem to be a general thing with that attribute. I haven't had the time to look at your attached project yet I'm afraid but hopefully will have soon.

The project we used in this extension to do some verifications use them as well as you can see here: https://github.com/formulahendry/vscode-dotnet-test-explorer/tree/master/test/xunittests

**Comment by MatthewS2077** [comment]
@stefanforsberg Thanks. I downloaded the xunittests project. The issue is with the namespace. In your case the namespace is 'non-dotted', ie just simply XunitTests.
If I change your namespace in Testclass1.cs from `namespace XunitTests` to `namespace My.Xunit.Tests` then the Test Explorer has the same issue I'm having in my project.

**Comment by stefanforsberg** [comment]
@MatthewS2077 Thank you! There are a few things working together to cause the issues you're seeing.

One of the problem stems from the fact that xunit/dotet test reports test results in a slightly unexpected matter when namespaces contains dots (just for Facts, not for the Theory which you also noticed). We are aware of the issue now but I can't promise the fix will be quick. Making our extension work around other frameworks is usually time consuming and not really prioritized.

**Comment by WallaceKelly** [comment]
This is happening to me too. In my case...

- the presence or absence of dots in the namespace has no effect.
- if I open a VS Code _workspace_ which includes both my library project and my test project, the tests are listed twice.
- if I open just the test project _folder_, the tests are listed once.

**Comment by stefanforsberg** [comment]
@WallaceKelly Interesting, is this also after you've actually tried to run tests or are they duplicated after test discovery is done as well?

**Comment by WallaceKelly** [comment]
@stefanforsberg  I'm seeing duplicates after both discovery and run.

![dups-before](https://user-images.githubusercontent.com/698424/55491858-3c1e7e00-5604-11e9-9878-997fe2dd28cd.PNG)

![dups-after](https://user-images.githubusercontent.com/698424/55492029-869ffa80-5604-11e9-91f9-40ada5524d12.PNG)

**Comment by MatthewS2077** [comment]
I wasn't using a workspace, just opening VSCode in the root folder of my project (my project and the project.tests folders being sub-folders of the root folder). 
Maybe its workspace related? 
BTW do you get duplicates if you use `[Theory][InlineData()]` instead of `[Fact]` ?

**Comment by WallaceKelly** [comment]
@MatthewS2077 I'm using MS Test, [TestClass] and [TestMethod], not xUnit.

**Comment by stefanforsberg** [comment]
@WallaceKelly Thanks for reporting, I'll take a look.

**Comment by stefanforsberg** [comment]
@WallaceKelly Haven't been able to reproduce this one yet I'm afraid.

If you can share your project or create a small new project where you get this error it would be great.

**Comment by WallaceKelly** [comment]
@stefanforsberg 

1. Extract [tests-duplicated.zip](https://github.com/formulahendry/vscode-dotnet-test-explorer/files/3058946/tests-duplicated.zip)
2. In VS Code, open the workspace library\library.code-workspace
3. Observe the single test listed twice.

After creating this, I'm able to hypothesize that it is related to having both a *.code-workspace and a *.sln file. (I occasionally have both when switching back and forth between VS and VS Code.)

Notice in the image below that the test library is queried twice. 

![Capture](https://user-images.githubusercontent.com/698424/55800753-71164f00-5aa2-11e9-86f3-51bc8ddf4c54.PNG)

**Comment by WallaceKelly** [comment]
In the tests-duplicated project, setting the following...

    "dotnet-test-explorer.testProjectPath": "**/*-tests.csproj",

...removed the duplicate tests. (This setting is also a workaround for #203.)

**Comment by WhatFreshHellIsThis** [comment]
Is this closed because @WallaceKelly  proposed a setting change to work around it or because it was fixed or some other reason?

**Comment by MatthewS2077** [comment]
I think its a dup of #201

**Comment by stefanforsberg** [comment]
@WhatFreshHellIsThis Ah yes, this issue contained two separate causes for the the same behavior. What you called a proposed setting change is actually what the extension requires atm (if you have multiple projects in a workspace we need to know which ones of those have tests). 

The original issue is as @MatthewS2077 the same as #201.
