### ISSUE TITLE
See test reference in the source code

### ISSUE THREAD

**Issue by seriouz** [formulahendry/vscode-dotnet-test-explorer#161]
Would it be possible for dotnet-test-explorer to show in my project's c# functions if they are covered by a test or even if the test is passing, like "live unit testing" feature of vs enterprise?

![image](https://user-images.githubusercontent.com/4722613/47813558-c019c480-dd4b-11e8-8096-d4d357aa1210.png)

**Comment by stefanforsberg** [comment]
I think people are doing something similar to this (not sure how it looks like exactly in vscode). Check the settings in https://github.com/formulahendry/vscode-dotnet-test-explorer/tree/master/test/xunittests (both the csproj and the .vscode/settings file). Then people are using one of the gutter plugins in vscode (maybe https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters?)

**Comment by janaka** [comment]
Agree with @stefanforsberg. There are other plugin's that focus on coverage visualisation. Closing based on this.
