### ISSUE TITLE
Running tests from a workspace instead of from a folder

### ISSUE THREAD

**Issue by sundriftproductions** [formulahendry/vscode-dotnet-test-explorer#166]
I have a workspace with projects set up like this:

	{	
		"folders": [
			{
				"path": "../MassiveRepo/MyCompany.ProjectDirectory01"
			},
			{
				"path": "../MassiveRepo/MyCompany.ProjectDirectory02"
			},
			{
				"path": "../MassiveRepo/MyCompany.ProjectDirectory03"
			},
			{
				"path": "../MassiveRepo/MyCompany.ProjectDirectory04"
			},
		],
	}

Most (but not all) of these paths have a `/test` directory directly underneath. So in Visual Studio Code's `settings.json` file, I have this:

     "dotnet-test-explorer.testProjectPath": "test"

When I load the workspace in Visual Studio Code and click on the .NET Test Explorer icon, the test project under the very first directory listed in the workspace loads. This is what is displayed in the Output window under Test Explorer:

	Starting extension
	Finding projects for pattern c:/code\MassiveRepo\MyCompany.ProjectDirectory01/test
	Found 1 matches for pattern
	Evaluating match c:/code/MassiveRepo/MyCompany.ProjectDirectory01/test
	Adding directory c:/code/MassiveRepo/MyCompany.ProjectDirectory01/test
	Executing dotnet test -t -v=q in c:/code/MassiveRepo/MyCompany.ProjectDirectory01/test
	Discoverd tests with xunit. Found 5 in 1 directories

So far, so good. The problem is...how do I run tests that belong to any of the other projects in my workspace with .NET Test Explorer? I can't get to `ProjectDirectory02`, `ProjectDirectory03`, or `ProjectDirectory04` unless I put that path as the first folder in the workspace file or open up the project as a folder instead of part of a workspace.

Ideally, I would like to see all of the tests for all of the workspace's projects in .NET Test Explorer, so I can do a "Run All Tests" and make sure everything passes. Or maybe there's a way to do this and I don't have something set up correctly. Any suggestions?

**Comment by stefanforsberg** [comment]
Hello! We do not currently support multiple workspaces but it's in the works for the next release. No promises though =)

**Comment by swASO** [comment]
Hi @stefanforsberg 
dont work for me 

`"dotnet-test-explorer.testProjectPath": "**/*.test.csproj"`

```
Finding projects for pattern c:/DEV\platform\dotnet\matchmaking-service/**/*.test.csproj
Found 1 matches for pattern in folder c:\DEV\platform\dotnet\matchmaking-service
Finding projects for pattern c:/DEV\platform\dotnet\lib/**/*.test.csproj
Found 16 matches for pattern in folder c:\DEV\platform\dotnet\lib
```

```
"folders": [
		{
			"path": "../matchmaking-service"
		},
		{
			"path": "../lib"
		},
	]
```
![image](https://user-images.githubusercontent.com/4096843/48497666-e99b1b80-e834-11e8-8dc7-0e4ff205e5ea.png)

**Comment by stefanforsberg** [comment]
@swASO You should see more logging that looks something like this after the ones you wrote above

Evaluating match d:/dev/vscode-dotnet-test-explorer/test/xunittests/
Adding directory d:/dev/vscode-dotnet-test-explorer/test/xunittests/
Evaluating match d:/dev/vscode-dotnet-test-explorer/test/nunit/
Adding directory d:/dev/vscode-dotnet-test-explorer/test/nunit/
Evaluating match d:/dev/vscode-dotnet-test-explorer/test/fsxunittests/
Adding directory d:/dev/vscode-dotnet-test-explorer/test/fsxunittests/
Evaluating match d:/dev/vscode-dotnet-test-explorer/test/mstest/
Adding directory d:/dev/vscode-dotnet-test-explorer/test/mstest/
Executing dotnet test -t -v=q in d:/dev/vscode-dotnet-test-explorer/test/xunittests/

etc. Would you mind pasting the rest of the log?

**Comment by swASO** [comment]
yes, sorry

```
Finding projects for pattern c:/DEV\platform\dotnet\matchmaking-service/**/*.test.csproj
Found 1 matches for pattern in folder c:\DEV\platform\dotnet\matchmaking-service
Finding projects for pattern c:/DEV\platform\dotnet\lib/**/*.test.csproj
Found 16 matches for pattern in folder c:\DEV\platform\dotnet\lib
Evaluating match c:/DEV/platform/dotnet/matchmaking-service/matchmaking.service.test/matchmaking.service.test.csproj
Adding directory c:/DEV/platform/dotnet/matchmaking-service/matchmaking.service.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.aws.auth.security/flowfact.aws.auth.security.test/flowfact.aws.auth.security.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.aws.auth.security/flowfact.aws.auth.security.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.common.flowdsl/flowfact.common.flowDsl.test/flowfact.common.flowDsl.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.common.flowdsl/flowfact.common.flowDsl.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.configuration.properties/flowfact.configuration.properties.test/flowfact.configuration.properties.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.configuration.properties/flowfact.configuration.properties.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.configuration/flowfact.configuration.test/flowfact.configuration.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.configuration/flowfact.configuration.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.consul.client/flowfact.consul.client.test/flowfact.consul.client.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.consul.client/flowfact.consul.client.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.elasticsearch/flowfact.elasticsearch.test/flowfact.elasticsearch.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.elasticsearch/flowfact.elasticsearch.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.extensions/flowfact.extensions.test/flowfact.extensions.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.extensions/flowfact.extensions.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.kafka.email.entity.service/flowfact.kafka.email.entity.service.test/flowfact.kafka.email.entity.service.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.kafka.email.entity.service/flowfact.kafka.email.entity.service.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.kafka.entity.service/flowfact.kafka.entity.service.test/flowfact.kafka.entity.service.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.kafka.entity.service/flowfact.kafka.entity.service.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.kafka/flowfact.kafka.test/flowfact.kafka.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.kafka/flowfact.kafka.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.redis/flowfact.redis.test/flowfact.redis.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.redis/flowfact.redis.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.services.attributes/flowfact.services.attributes.test/flowfact.services.attributes.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.services.attributes/flowfact.services.attributes.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.services.clients/flowfact.services.clients.test/flowfact.services.clients.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.services.clients/flowfact.services.clients.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.services.logging/flowfact.services.logging.test/flowfact.services.logging.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.services.logging/flowfact.services.logging.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.services.sharedcontrollers/flowfact.services.sharedControllers.test/flowfact.services.sharedControllers.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.services.sharedcontrollers/flowfact.services.sharedControllers.test
Evaluating match c:/DEV/platform/dotnet/lib/flowfact.services.startup/flowfact.services.startup.test/flowfact.services.startup.test.csproj
Adding directory c:/DEV/platform/dotnet/lib/flowfact.services.startup/flowfact.services.startup.test
Executing dotnet test -t -v=q in c:/DEV/platform/dotnet/matchmaking-service/matchmaking.service.test
```

**Comment by sundriftproductions** [comment]
Hi @stefanforsberg -- 

Thanks for the update (and for implementing my request). The tests now seem to run fine using a workspace, but I cannot go to a test via Test Explorer. If I right-click on a test and choose "Go to Test" or double-click on a test, I get the message `Could not find test (no symbols found)`. I'm able to do this when opening a test via a folder, just not with a workspace.

**Comment by stefanforsberg** [comment]
@sundriftproductions This is because of limitations with the Omnisharp extension which we use to find symbols. Apparently omnisharp is just running for one of the workspaces, you can see which one by looking at the bottom of vscode

![image](https://user-images.githubusercontent.com/358570/48658512-6c91c100-ea43-11e8-9617-dd1b0c7a7d6c.png)

That means we can only find symbols for the currently selected workspace unfortunately 😞
