### ISSUE TITLE
Test Categories 

### ISSUE THREAD

**Issue by pmorelli92** [formulahendry/vscode-dotnet-test-explorer#167]
All the testing frameworks (nUnit, xUnit, MS) allows the setting up of categories in order to group tests by functionality or relating them to something (could be a feature, a bug, etc)
For example in xUnit

```
[Fact]
[Trait("Category", "Foo")]
public void One_Test_Relating_Foo() {}
```

```
[Fact]
[Trait("Category", "Foo")]
public void Other_Test_Relating_Foo() {}
```

And then, you can run all tests that relates to "Foo" hierarchy.
Is there any plan on implementing this?

**Comment by stefanforsberg** [comment]
Hello! There are no plans from me to implement this in the foreseeable future. But we love pull requests =)
