### ISSUE TITLE
Tests are not discovered in multi-root workspace if at least one folder doesn't contain sln/csproj

### ISSUE THREAD

**Issue by nvborisenko** [formulahendry/vscode-dotnet-test-explorer#171]
I have multi-root workspace with several folders, and one folder doesn't have `sln` or `csproj` file.

Output:
```
Executing dotnet test -t -v=q in c:/ProjA/
Executing dotnet test -t -v=q in c:/ProjB/
Executing dotnet test -t -v=q in c:/ProjC/
[ERROR] Error while executing dotnet test -t -v=q - MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

If I remove the folder without `sln` file, tests are successfully discovered.

Expected behaviour:
Discovered tests are shown with warning message in output.

**Comment by stefanforsberg** [comment]
Would it be possible to add a folder/csproj pattern glob pattern perhaps?

**Comment by nvborisenko** [comment]
Didn't verify, but I think it doesn't help. My folder in multi-root workspace doesn't contain `sln` or `csproj` file at all. I think this is a root of issue.

**Comment by stefanforsberg** [comment]
Given this multi root workspace:
folderA\A.csproj
folderB\B.csproj
folderC\(not a dotnet project)

If you set the Test Project Path to *.csproj the test explorer will only try to initiate itself in the folderA and folderB. If you set the Test project path to a glob that matches your folders/files it should work.

**Comment by nvborisenko** [comment]
Even if it works I would prefer that it should work by default. Because of by default I see tests with "correct" folders. But as soon as I add new "incorrect" folder, I see no tests at all.
