### ISSUE TITLE
--no-build doesnt prevent build

### ISSUE THREAD

**Issue by guylando** [formulahendry/vscode-dotnet-test-explorer#173]
Even when adding --no-restore and --no-build parameters, there is still a separate dotnet build command executing when executing a test case. Plugin version 0.6.0.

**Comment by stefanforsberg** [comment]
Ah yes, those commands are only added to the dotnet test command. We split those into a dotnet build and then a dotnet test to be able to detect if a build fails or not.

**Comment by guylando** [comment]
@stefanforsberg well seems that if a user passes --no-build flag then the code should assume the user took care of the build and not call the dotnet build
