### ISSUE TITLE
Colors don't update even if all tests pass

### ISSUE THREAD

**Issue by bojobiscuit** [formulahendry/vscode-dotnet-test-explorer#180]
When I run the tests everything passes. But the parent branches stay red while the tests themselves are green. 

![screen shot 2019-01-30 at 12 01 08 pm](https://user-images.githubusercontent.com/46871428/51998490-c886b600-2486-11e9-9336-11bc043f6ee7.png)

It happens when any test fails. When the tests pass afterwards, the parent brackets stay red. 

Edit: Following up, this actually fixes when I reset VSCode. But I figured it's still important. 

Edit2: Just created another test class, failed, and then passed. And now all the colors are updated properly again. Not really sure why it wouldn't trigger the initial time.

**Comment by stefanforsberg** [comment]
I have an idea about what's causing this. When you run a subset of tests (for instance test under the AddCoursesDt..) we only update the nodes that were part of the test run. The extension is not currently smart enough to realise that the last test run might also change the state of tests higher up in the tree. If you run all tests the color should properly reflect the current state. It's not ideal, I know, but it's a workaround.

**Comment by bojobiscuit** [comment]
Still random after trying a couple of things, but I'll keep looking. Thanks for trying!

**Comment by stefanforsberg** [comment]
What testing framework do you use btw?

**Comment by bojobiscuit** [comment]
> What testing framework do you use btw?

XUnit
