### ISSUE TITLE
Extension host terminated unexpectedly in VSCode Version 1.31.0 (1.31.0)

### ISSUE THREAD

**Issue by kfinley** [formulahendry/vscode-dotnet-test-explorer#182]
After updating to Version 1.31.0 (1.31.0) something broke. Isolated the dotnet test explorer by disabling all other installed extensions. Here's the info available from Developer Tools.

Environment: 
MacOS v10.14.2
Node v10.12.0
VSCode v1.31.0

INFO no standard startup: panel is active
log.ts:173   ERR An unknown error occurred. Please consult the log for more details.
extensionService.ts:457 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ extensionService.ts:457
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:40
extensionHost.ts:231 Extension Host
extensionHost.ts:232 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/xxxx/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/xxxx/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

**Comment by stefanforsberg** [comment]
This seems to be the root cause Microsoft/vscode/issues/64981. I will try to get the fix in asap, bit hectic at the moment so I can't promise it will be quick I'm afraid.

**Comment by stefanforsberg** [comment]
Hey, new version was just released which hopefully works better.

**Comment by kfinley** [comment]
Sorry I never followed up on this but the newer version unfortunately didn't solve the issue. I've just being working without test explorer on my mac (which is a bummer). I'm still getting the same error as before with latest VSCode, MacOS, and node v12.2.0.
