### ISSUE TITLE
testProjectPath works inconsistently between Explorer and Terminal

### ISSUE THREAD

**Issue by DrStriate** [formulahendry/vscode-dotnet-test-explorer#19]
I like your plugin but for my project which is organized in a folder hierarchy like
Root -> UnitTests
         -> Code, etc

When I load the folder Root the Unit tests fill in the .Net Test Explorer but when I try and run it tries all of the projects that are peer to UnitTests (e.g. Code, etc.) and bloats the Terminal with bogus build errors "No test found" for every folder. 

But if I set "dotnet-test-explorer.testProjectPath": "./UnitTests" in Settings.json, it builds and runs the unit tests just fine... but nothing in the .Net Test Explorer

How can I tell your tool that the test .csproj is in the UnitTests folder without breaking the Explorer?

**Comment by formulahendry** [comment]
> But if I set "dotnet-test-explorer.testProjectPath": "./UnitTests" in Settings.json, it builds and runs the unit tests just fine... but nothing in the .Net Test Explorer

Hi @DrStriate , which folder did you open?

> When I load the folder Root the Unit tests fill in the .Net Test Explorer but when I try and run it tries all of the projects that are peer to UnitTests (e.g. Code, etc.) and bloats the Terminal with bogus build errors "No test found" for every folder.

Could you please add punctuation for your sentence? It is a little hard to read..

**Comment by DrStriate** [comment]
Hi - I've tried opening the root folder (that holds the UnitTests folder) and the UnitTests folder. With the Root folder open, then I can see the unit tests in .Net Test Explorer but when I try and run them (dotnet test) each non-unit test folder tries to build then throw errors about not being unit test projects.. If i open the UnitTests folder, then the opposite happens: the tests run fine w 'dotnet test' but I get nothing in the .Net Test Explorer. How should I get both the Explorer to display and the tests to run?

**Comment by DrStriate** [comment]
I think I have it working now. Thanks.

**Comment by formulahendry** [comment]
Good to know. Closing this issue then.
