### ISSUE TITLE
Add Problems setting no longer functions in 0.6.5

### ISSUE THREAD

**Issue by cparker15a** [formulahendry/vscode-dotnet-test-explorer#191]
Since updating to version 0.6.5 of the extension I no longer receive error messages in the "Problems" tab of the VSCode console. Looking through commit #190 it appears you removed a block of code that returned a result from a promise (src/testCommands.ts line 184-186) and it seems like a very likely candidate for causing this bug. Rolling back to version 0.6.4 fixes the issue entirely.

**Comment by stefanforsberg** [comment]
Just noticed this today as well, thank for reporting it!

**Comment by stefanforsberg** [comment]
Fixed with 0.6.6
