### ISSUE TITLE
colored dotnet-test-explorer.codeLensFailed

### ISSUE THREAD

**Issue by b3b00** [formulahendry/vscode-dotnet-test-explorer#202]
hello,

Is there a way to display a colored `dotnet-test-explorer.codeLensFailed` ?
I explained : 
When letting `dotnet-test-explorer.codeLensFailed` empty a red cross is displayed
When setting it to say 'too bad' then the text is gray displayed.
IS there a way to choose a color (red would be nice) ?

The same apply to `dotnet-test-explorer.codeLensPassed`

**Comment by stefanforsberg** [comment]
Hello! There doesn't appear to be a way to change the display of the code lens (at least not according to a quick search on google I did now). We use the emojis as default just because they add some color and imho are easier to see than text.
