### ISSUE TITLE
Tests display as still running even after they have completed

### ISSUE THREAD

**Issue by WallaceKelly** [formulahendry/vscode-dotnet-test-explorer#203]
(Similar symptoms to #120, but not related to disposing resources.)

1. Extract [test-does-not-complete.zip](https://github.com/formulahendry/vscode-dotnet-test-explorer/files/3059460/test-does-not-complete.zip)
2. In VS Code, open library/library.code-workspace.
3. In .NET Test Explorer, start the test.
4. Observe the spinning icon never stops spinning, even though the Test Explorer Output says that the test completed successfully.

![Capture](https://user-images.githubusercontent.com/698424/55807973-294af400-5ab1-11e9-8cf1-e0da9ce66a90.PNG)

**Comment by stefanforsberg** [comment]
Hello! Have you tried this https://github.com/formulahendry/vscode-dotnet-test-explorer#test-result-is-not-shown-in-codelens--tree?

**Comment by WallaceKelly** [comment]
@stefanforsberg, like this?

![Capture2](https://user-images.githubusercontent.com/698424/55818867-a1bbb000-5ac5-11e9-9678-5c125945c843.PNG)

**Comment by stefanforsberg** [comment]
Yep that's the one. I'm guessing it still doesn't work for you? 

![image](https://user-images.githubusercontent.com/358570/55822862-c84b0c80-5b00-11e9-8515-72fe8caefd22.png)

**Comment by WallaceKelly** [comment]
I've tested 3 or 4 times more and found another clue. It consistently fails if I press the "Run All Tests" button. It consistently succeeds if I press the "Run Test" button. Do you @stefanforsberg see the same?

![Capture4](https://user-images.githubusercontent.com/698424/55824754-86a36d00-5ad2-11e9-8fa8-4c21ff2d3972.PNG)

![Capture3](https://user-images.githubusercontent.com/698424/55824745-830fe600-5ad2-11e9-83f5-e0e3a7219ca1.PNG)

**Comment by stefanforsberg** [comment]
@WallaceKelly I'm afraid that does not trigger the behavior for me. It works as expected for both the run all and run test button.

**Comment by WallaceKelly** [comment]
I tested on two unrelated machines (one is enterprise-managed Windows 7; one is personal home computer Windows 10) and I get the same behavior. Here is a video (no audio) from the Windows 10 box. Perhaps there will be a clue in it. 

https://s3.amazonaws.com/temp.bluerockresearch.com/test-does-not-complete.mp4

Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

Version: 1.33.0 (user setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by stefanforsberg** [comment]
Ah yes, I have an idea what's happening. If you add the setting testprojectpath to point to your test project (something like "dotnet-test-explorer.testProjectPath": "**/*-tests.csproj"), does it work as expected with the run all button then?

**Comment by WallaceKelly** [comment]
@stefanforsberg, yes, that fixed it.

![Capture5](https://user-images.githubusercontent.com/698424/55894943-2f140880-5b89-11e9-9ede-833d9c1c0147.PNG)

**Comment by stefanforsberg** [comment]
Thank you for your help in narrowing this issue down, really appreciate it.

As for the actual solution what we can do in the short term is to be clearer in the known issues that if you have multiple multiple workspaces it's important that you only point to the actual test projects for the extension to work as expected.
