### ISSUE TITLE
XUnit - "Go To Test" error with parenthesis - Could not find test (no symbols matching)

### ISSUE THREAD

**Issue by mhenry42** [formulahendry/vscode-dotnet-test-explorer#206]
With XUnit, if I create a [Theory] test where the [InlineData] has an open parenthesis "(" or a closing parenthesis followed by a character ")a", you will get a "Could not find test (no symbols matching)" when using the "Go To Test" feature.

1. dotnet version 2.2.202
2. XUnit 2.4.1
3. Repo link to recreate the issue:  https://github.com/mhenry42/DotNetTestExplorerTests

![X7SihdNiOq](https://user-images.githubusercontent.com/11511818/56223409-4e041600-6033-11e9-8f78-126aec037deb.png)

**Comment by alanfan2019** [comment]
The same problem as you
