### ISSUE TITLE
MSBUILD : error MSB1008 Only one project can be specified.

### ISSUE THREAD

**Issue by jjthiago** [formulahendry/vscode-dotnet-test-explorer#213]
Hi,

The plugin is looking for the tests in the directory set in dotnet-test-explorer.testProjectPath.
But it does not appear. When I run dotnet test -t -v = q in c: /Users/MyUser/Workspace/Project/Project.csproj I see the error
MSBUILD : error MSB1008 Only one project can be specified.

**Comment by stefanforsberg** [comment]
Hmm, we can't really do anything against build errors I'm afraid. Or maybe I misunderstand your question?

**Comment by Kash0321** [comment]
I'm experimented same issue, and I think that it's not a problem with build errors… Tests executes properly on Visual Studio, and the command 'dotnet test' executes right too…

**My .vscode\settings.json content:**
```json
{
    "dotnet-test-explorer.testProjectPath": "*Tests/*Tests.csproj"
}
```
**TestExplorer log output while discovering tests:**
```
Finding projects for pattern c:/work\testexplorerissue/*Tests/*Tests.csproj
Found 1 matches for pattern in folder c:\work\testexplorerissue
Evaluating match c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests/TestExplorerIssue.Lib.Tests.csproj
Adding directory c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests
Executing dotnet test -t -v=q in c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests
```
Then, in .NET TEST EXPLORER panel you can see: *Please, open or set the test project and ensure your project compiles*

The problem, I think, is with the execution of  `dotnet test -t -v=q in c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests` command. It throws the following error: 
**MSBUILD : error MSB1008 Only one project can be specified.**

Attached, I send you a zipped solution that reproduces it: [testexplorerissue.zip](https://github.com/formulahendry/vscode-dotnet-test-explorer/files/3389530/testexplorerissue.zip)

**Comment by jjthiago** [comment]
Hello, Sergio, thanks for replying.

I managed to fix the problem. 😊

Enviado do Email para Windows 10

De: Sergio Castillo
Enviado:domingo, 14 de julho de 2019 03:49
Para: formulahendry/vscode-dotnet-test-explorer
Cc:Thiago Santos; Author
Assunto: Re: [formulahendry/vscode-dotnet-test-explorer] MSBUILD : errorMSB1008 Only one project can be specified. (#213)

I'm experimented same issue, and I think that it's not a problem with build errors… Tests executes properly on Visual Studio, and the command 'dotnet test' executes right too…
My .vscode\settings.json content:
{

    "dotnet-test-explorer.testProjectPath": "*Tests/*Tests.csproj"

}
TestExplorer log output while discovering tests:
Finding projects for pattern c:/work\testexplorerissue/*Tests/*Tests.csproj

Found 1 matches for pattern in folder c:\work\testexplorerissue

Evaluating match c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests/TestExplorerIssue.Lib.Tests.csproj

Adding directory c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests

Executing dotnet test -t -v=q in c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests

Then, in .NET TEST EXPLORER panel you can see: Please, open or set the test project and ensure your project compiles
The problem, I think, is with the execution of dotnet test -t -v=q in c:/work/testexplorerissue/TestExplorerIssue.Lib.Tests command. It throws the following error:
MSBUILD : error MSB1008 Only one project can be specified.
Attached, I send you a zipped solution that reproduces it: testexplorerissue.zip

**Comment by Kash0321** [comment]
Oh, can you share with me how to fix it? I have no success...

**Comment by CyberGuerro** [comment]
Issue persist on 0.7.5 (linux environment).   Issue is caused by "in" parameter. If you remove "in" in this way:
WRONG
`dotnet test -t -v=q in c:/work/testexplorerissue`
CORRECT
`dotnet test -t -v=q c:/work/testexplorerissue`

Tests are listed correctly, infact in online help (dotnet test --help), there is no "in" parameter reference and probably MSBuild considers "in" parameter as folder together real folder (total 2 fodlers)
