### ISSUE TITLE
[Enhancement] AutoWatch - Run modified tests instead of all tests

### ISSUE THREAD

**Issue by AlexTeixeira** [formulahendry/vscode-dotnet-test-explorer#216]
Hi,

### Current Behavior

Currenlty **AutoWatch** works good, but I think some improvements can be done.

When you save a file, all founds projects are rerun with the command **dotnet test**

But if I run the tests from the play button : 

![image](https://user-images.githubusercontent.com/6555080/57935958-371b4280-78c3-11e9-9516-a5e0cd0bc3e9.png)

It add a filter to the command : 
`
--filter "FullyQualifiedName~Project.Namespace.UserService_Test"`

### Expected Behavior 

**Scenario:** Developer was updating one or multiples test
**Given:** I save the changes made in appropriated files
**Then:** Plugin should run only the modified tests

**Exemple :** 

- I update the tests **User_WantTobeCalled_ShouldHaveNumberPhone** and **Order_AddItem_ShouldhaveNewItem**
- I save the files **UserTest** and **OrderTest**
- Only **User_WantTobeCalled_ShouldHaveNumberPhone** and **Order_AddItem_ShouldhaveNewItem** should run 

This will improve tests feedback and avoid CPU overhead on running tests multiple times.

I think this features can be split in two steps.

### First Step

Update the whole files instead of the updated tests. Plugin should be able to detect the updated files and add it in **dotnet test --filter**

### Second Step

Try to get the modified test to run only the tests instead of the whole class under the file that was updated. 
I think this one is quite more difficult to achieve.

Currently, I don't have enough time to have a look to this feature. But I think it can be a good enhancement.

**Comment by stefanforsberg** [comment]
Hello @AlexTeixeira and thank you for your suggestions =)

When it comes to dotnet watch functionality we're just using what the build in tooling provides us. While you're suggestions sounds excellent I think they are better directed to the aspnetcore repository at https://github.com/aspnet/AspNetCore/tree/master/src/Tools/dotnet-watch.

**Comment by AlexTeixeira** [comment]
Hi,

Thanks for the information.
I opened an issue to AspNetCore repo :

https://github.com/aspnet/AspNetCore/issues/new?template=feature_request.md
