### ISSUE TITLE
Where to set dotnet-test-explorer.testProjectPath ?

### ISSUE THREAD

**Issue by khteh** [formulahendry/vscode-dotnet-test-explorer#217]
Hello! Thanks for opening a new issue. Before you do so however could you please:

1. Check the known issues -> https://github.com/formulahendry/vscode-dotnet-test-explorer#known-issues
2. Check for other opened or closed issue matching yours?

If you open an issue please include
1. Dotnet sdk version: 2.2.204
2. Unit test framework and relevants versions of that
3. A link to a repo that replicated the issue

Thanks a lot!

**Comment by stefanforsberg** [comment]
Hello @khteh, I'm afraid I don't quite understand your question?

**Comment by shpsyte** [comment]
This is an option, so you need to open your setting.json and put the config.
In this case, will get all project that has a "Test.csproj" in the name...

"dotnet-test-explorer.testProjectPath": "**/*Test.csproj"

**Comment by ChaoPiPi** [comment]
I also have this problem, if it is set up “dotnet-test-explorer.testProjectPath”：“** / * Test.csproj” , it will not be detected.

**Comment by icefire1** [comment]
While @shpsyte is very much correct I too did spend a couple minutes trying to figure out exactly where to setup my glob pattern. Go to your user settings in VSCode (bottom left) and go to Extensions > .NET Core Test Explorer. One of the last configs is the "Test Project Path" in which you must insert your glob pattern. This pattern fit my case: `**/*Tests.csproj`.

**Comment by rdkleine** [comment]
> While @shpsyte is very much correct I too did spend a couple minutes trying to figure out exactly where to setup my glob pattern. Go to your user settings in VSCode (bottom left) and go to Extensions > .NET Core Test Explorer. One of the last configs is the "Test Project Path" in which you must insert your glob pattern. This pattern fit my case: `**/*Tests.csproj`.

This should be in the extension description. I had to google this.

**Comment by mgwelch** [comment]
Could this not be in the README?

**Comment by mgwelch** [comment]
> While @shpsyte is very much correct I too did spend a couple minutes trying to figure out exactly where to setup my glob pattern. Go to your user settings in VSCode (bottom left) and go to Extensions > .NET Core Test Explorer. One of the last configs is the "Test Project Path" in which you must insert your glob pattern. This pattern fit my case: **/*Tests.csproj.

None of this exists. There is no such setting.

**Comment by khteh** [comment]
Why is this closed?

**Comment by mgwelch** [comment]
> Why is this closed?

No idea, I don't understand how this is a 5 star extension. I have no idea how to get it to work. The issue template takes you to a page of 20 settings with no explanation of which of them you should be worried about. Then a dozen issues. The readme talks about a setting that doesn't seem to exist.

And none of my frustration is the author's fault. I'm sure this is an excellent project. But trying to whip out a quick dotnet app using VS Code and wishing I'd had just used Visual Studio instead.

**Comment by stefanforsberg** [comment]
@khteh We did some improvements guiding users to the settings when the extension can not find any tests and the comments above also answered your question. What action would you propose in order for it to be closed?

**Comment by khteh** [comment]
@stefanforsberg I asked why it was closed because I see questions and comments after it was closed. I have not tried the comments made here because I have switched to using Visual Studio 2019 on Windows 10. Hopefully I don't bump into the same problem when I switch to VSCode on Linux again one day and if that happens, I will ask again why this is closed. Thanks.
