### ISSUE TITLE
CodeLens display is broken (show status on separate line).

### ISSUE THREAD

**Issue by guillaume86** [formulahendry/vscode-dotnet-test-explorer#218]
It seems the CodeLens display is broken, in place of appending the status at the end of the existing CodeLens line, a new line is created, which looks pretty bad and use a lot of space.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/441850/58754266-b36d7280-84cc-11e9-9f81-c9893b4fb0cf.png)

update: If I put the attribute on the same line it works, I guess this extension is attaching the CodeLens to a different node than omnisharp and that causes the issue.

**Comment by guillaume86** [comment]
So I played a bit with the code and it looks like replacing `symbol.documentSymbol.range` by `symbol.documentSymbol.selectionRange`  in https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/3238f29517fcddc02e0afca28cc8c5909d6f87f4/src/testStatusCodeLensProvider.ts  is fixing the issue.

**Comment by stefanforsberg** [comment]
Thanks for figuring out a solution, I'll take a look at this in the coming days!
