### ISSUE TITLE
Bug in the name project

### ISSUE THREAD

**Issue by anton-compradon** [formulahendry/vscode-dotnet-test-explorer#221]
Hi, Fix a bug in "dotnet-test-explorer.testProjectPath": "..\\.csproj".
If my project name is ".csproj", then test explorer is not work.

**Comment by stefanforsberg** [comment]
Hello! Can you please provide a project that reproduces the issue?

**Comment by compradon** [comment]
> Hello! Can you please provide a project that reproduces the issue?

Hello! https://github.com/compradon/demo-test-explorer
