### ISSUE TITLE
Test Cases are being duplicated multiple times

### ISSUE THREAD

**Issue by whizkidwwe1217** [formulahendry/vscode-dotnet-test-explorer#249]
![image](https://user-images.githubusercontent.com/1977391/78022859-40e94f80-7388-11ea-979f-ef3f91fd5f26.png)

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100     
 Commit:    cd82f021f4  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18363
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by arakis** [comment]
I can confirm that this happens to me to:

![image](https://user-images.githubusercontent.com/1831942/78452292-c3288b00-768a-11ea-988f-064a03d20172.png)

**Comment by eddex** [comment]
I have the same issue.

![image](https://user-images.githubusercontent.com/5302085/80068246-922bcf80-853f-11ea-8b89-c69aa27db08f.png)

**Comment by stefanforsberg** [comment]
If you could write a small example that replicates this error that would be super.

**Comment by eddex** [comment]
I created a new `MsTest Test Project (.NET Core)`. Nothing was chnaged except for an `Asstert.IsTrue(true)` in the only test in the project.

```csharp
namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.IsTrue(true);
        }
    }
}
```

This is what I see in the Test Explorer window:
![image](https://user-images.githubusercontent.com/5302085/82115243-dc305b80-9761-11ea-9e31-49321c0408b4.png)

My Dotnet-test-explorerTest Project Path is set to `**/*Test*/*.csproj`

Here's the code: [UnitTestProject1.zip](https://github.com/formulahendry/vscode-dotnet-test-explorer/files/4638059/UnitTestProject1.zip)

**Comment by stefanforsberg** [comment]
Hmm, not able to reproduce this locally.

What is written when you click the "Show log" (the icon to the top right  in the extension area)?

For reference, this is what is written for me:

`Finding projects for pattern c:/SomePath\UnitTestProject1/**/*Test*/*.csproj
Found 1 matches for pattern in folder c:\SomePath\UnitTestProject1
Evaluating match c:/SomePath/UnitTestProject1/UnitTestProject1/UnitTestProject1.csproj
Adding directory c:/SomePath/UnitTestProject1/UnitTestProject1
Executing dotnet test -t -v=q in c:/SomePath/UnitTestProject1/UnitTestProject1
Executing dotnet vstest "c:\SomePath\UnitTestProject1\UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll" /ListFullyQualifiedTests /ListTestsTargetPath:"C:\Users\Stefan\AppData\Local\Temp\test-explorer-discover-xgYKLw\output.txt" in c:/SomePath/UnitTestProject1/UnitTestProject1`

**Comment by eddex** [comment]
Weird, I can't reproduce it anymore either. I changed the `Dotnet-test-explorer: Test Project Path` to `**/*Test*/*.csproj` from the default value when I tried it this morning.

**Comment by bjornbouetsmith** [comment]
I can confirm this also happens - it seem to be related to the Test project Path - if you write a proper glob it does not happen, i.e. for me this caused it:

**/*Tests*

Which found my test project called xxxTests.csproj

if I change the glob to:
**/*Tests*.csproj

I don't get any duplicated tests - so either its dotnet screwing up by finding many versions of the test dlls, i.e in obj/ bin/

where when you write a .csproj its intelligent enough to only the the output of the build.

Or its the extension that is finding too many files.

**Comment by eddex** [comment]
I quickly checked this again and can confirm @bjornbouetsmith's statement. 

When I set the glob pattern to `*Test*` the tests are found multiple times:
![image](https://user-images.githubusercontent.com/5302085/82183017-81c00800-98e5-11ea-9e8c-80369a55cab3.png)

With a propper glob pattern (e.g. `**/*Test*.csproj`) the issue is not present.

**Comment by GeorchW** [comment]
Okay, so it looks like this is caused by the glob globbing all the sub-items of a given path. In this case, we could just filter the globbing results and take the shortest prefix(es).
