### ISSUE TITLE
Is this extension going to maintained?

### ISSUE THREAD

**Issue by murbanowicz** [formulahendry/vscode-dotnet-test-explorer#251]
Hi,

It looks great (came across it today), but there is no updates for almost a year, issues backlog is piling up with pretty serious issues.
I would like to know if it is going to be maintained or not? 
I am not able to help with this unfortunatelly so no hard feeling please, I am just asking.

**Comment by stefanforsberg** [comment]
Hello and thanks for your very relevant question. I'm not the owner of the extension but I have been maintaining it for the last couple of years.

There are two main contributing factors to the lack of update from me:
1: _It's pretty feature complete at the moment._ It can run tests and report back the results which is what you can expect of a test runner 😄. If anything I'd like to remove features which are not really stable or works in slightly surprising ways (debug, multiple workspace, multiple test projects comes to mind)

2: _It works well enough for my use cases_. I'm using the extension almost daily at my job and mostly it works. I wish I had more time to devout to debugging how some third party system (the file system watcher with a specific dotnet sdk on a certain linux distribution) but the sad truth is that I don't.

I'm not sure if this is to be interpreted as that it is maintained or not.

**Comment by stefanforsberg** [comment]
One small addition. Most of the issues people are having can be directed back to the fact that in order for us to figure out the test results we need to write a file to disc and read that file. If the dotnet vstest had an option to get us the same information without resulting to writing and reading files that would help a ton. 

Any ideas in this department are greatly appreciated.

**Comment by SamazoOo** [comment]
Hi,

I'm trying to use the extension daily at my job and I miss some features:
 
- Filtering test with Trait, class, namespace for example
- Search test explorer
- Group test cases by class, namespace, class, state
- It would be so nice to have a visual resume of all test like VS
<img width="180" alt="image" src="https://user-images.githubusercontent.com/17595240/81040722-3ac92000-8eac-11ea-8257-b2f5acc1e341.png">

**Comment by GeorchW** [comment]
@stefanforsberg There are various PRs (I've added a few as well) that haven't been merged in almost a year. Don't get me wrong, I absolutely respect your decision when you're saying that you don't have the time to code and it works "well enough" for your use case. But could you at least allow others to work on this?

I mean, if you don't want to be responsible, that's fine as well, but I'm going to make a fork in that case.

**Comment by GeorchW** [comment]
@formulahendry @stefanforsberg The other problem is that there are potential security issues arising from countless dependencies that haven't been updated in a long time. NPM is already warning me about hundreds of vulnerabilities. There are multiple PRs by bots that that would fix them, but a simple `npm audit fix` or `npm update` would do, too. 

I'd love to do some bigger refactorings that remove some dependencies (e.g. chokidar, fkill), and update others (e.g. typescript) but I'll only start working on that as soon as I know where the future is headed for this project.

**Comment by stefanforsberg** [comment]
@GeorchW As I said I'm not the owner of this repository or the extension so I slightly recent the sentiment that I am not "allowing other" to work on the extension.

My view is this: If I don't have the time to check how an PR behaves or how it fits in with the vision for the extension I'd rather not except it because if I do and something fails I will not have the time to fix it and I've learned along the way that the person creating the PR might not be around to fix it either. So in a less than ideal world I've opted for keeping the extension as is even though it has meant that it's in a bit of a degraded state at the moment.

**But I love your passion for this and maybe we can start working together on making the extension better.** 

So I'll start with looking at the PR we have at the moment over the weekend and hopefully @formulahendry can chip in the thread as well. I haven't spoken to him in a while and since he is the person that actually deploys new versions of the extension he is an important person to have on board =)

**Comment by fuzzzerd** [comment]
Looks like the latest release on github is v0.7.0, latest on vs marketplace is v0.7.1, but the readme states v0.7.8. 

Where is the definitive place to get the latest version of the extension?

**Comment by stefanforsberg** [comment]
@fuzzzerd I'm not involved in the release process but as far as I know

* The latest (public) release is always on the marketplace and it's 0.7.1 as you say.

* As we're gearing up to release a new version the readme here on github is updated to reflect that version so depending on how long time it takes for @formulahendry to make the actual release from when I tell him there's a new release to make these may be out of sync for a few days.

If you want to run whatever is currently master (or any other commit in this repo) you can clone and build your own vsix file and install in your vscode if you follow the instructions here https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions.

On a couple of earlier occasions I've created such a vsix when we want people to beta test something.

Does that answer your question?

**Comment by fuzzzerd** [comment]
@stefanforsberg thanks it does. I was just confused/wondering what happened to v0.7.2 through v0.7.7/8. Seems like they weren't publicly released to the marketplace. I'll keep an eye on the marketplace.

**Comment by stefanforsberg** [comment]
0.7.2 is now released and should be available at the marketplace now.

I'll close this issue now, feel free to open separate issues if you feel there are still things that needs addressing from this issue.
