### ISSUE TITLE
Default VS Code `File: Open Recent... keybinding` is overidden

### ISSUE THREAD

**Issue by null-d3v** [formulahendry/vscode-dotnet-test-explorer#264]
The extension adds some chording shortcuts, `.NET: Debug Tests in Context` and `.NET: Run Tests in Context`, that are initiated with `CTRL + R`. This overrides the default VS Code `File: Open Recent...` / `workbench.action.openRecent` keybinding.

**Comment by stefanforsberg** [comment]
Hello! It's the C# extension (https://github.com/OmniSharp/omnisharp-vscode) that contributes those shortcuts.
