### ISSUE TITLE
Tests disappear after running all

### ISSUE THREAD

**Issue by tschissler** [formulahendry/vscode-dotnet-test-explorer#265]
I have these tests after discovery

![image](https://user-images.githubusercontent.com/11467601/83752748-52d9be00-a669-11ea-8ec6-aabde26792d4.png)

When I run them all, this is the result I see

![image](https://user-images.githubusercontent.com/11467601/83752791-65ec8e00-a669-11ea-93f2-ca51a76026f8.png)

I'm using dotnetcore 3.1.300-preview-015048

The code can be found here: https://github.com/proscrumdev/battleship-dotnetcore

**Comment by stefanforsberg** [comment]
Unfortunately the support for executing dotnet test against a solution (.sln) containing multiple test projects is lacking in that the tool overwrites the result for one projects when it starts on the next one in the solution. This is why only one is reported back in the tree.

Our solution to this is that you can specify which are your test projects with the setting *testProjectPath*. If you set that to `**/*Test*/*.csproj` it should work as expected.

https://github.com/formulahendry/vscode-dotnet-test-explorer#configuring-multiple-test-projects

**Comment by tschissler** [comment]
This solved the problem, thanks!
