### ISSUE TITLE
XUnit inline data is lost after test is run

### ISSUE THREAD

**Issue by stefanforsberg** [formulahendry/vscode-dotnet-test-explorer#267]
On test discovery
![image](https://user-images.githubusercontent.com/358570/83977743-3789df80-a903-11ea-9bb0-ae61d518f5eb.png)

After tests have run
![image](https://user-images.githubusercontent.com/358570/83977753-453f6500-a903-11ea-88a1-7c05d653aa83.png)

**Comment by GeorchW** [comment]
Uh, is this some issue with the new parsing? I'll have a look in the next few days I think

**Comment by stefanforsberg** [comment]
@GeorchW Hey, that is what I suspected at first but I tried it with the 0.7.1 release and it behaved in the same way. I didn't have a lot of time to troubleshoot over the weekend but will take a closer look this week.

**Comment by GeorchW** [comment]
Hmm, I can't reproduce this issue, even if I disable all other extensions.

**Comment by stefanforsberg** [comment]
Hmm, even if you open the xunit  solution that is included in the repo (in the test folder)?

**Comment by GeorchW** [comment]
Yes, that's the one I've tried it with.

**Comment by stefanforsberg** [comment]
Hmm intriguing!

I'll give it another go.

**Comment by GeorchW** [comment]
I mean, the bug is probably somewhere [here](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/4d71f133951bc80e452ce8a9a842cae3e3a7b870/src/dotnetTestExplorer.ts#L151). I'm not sure why it makes sense to reset the discovered tests when changing the results.

Oh, and while I'm at it, [this](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/4d71f133951bc80e452ce8a9a842cae3e3a7b870/src/dotnetTestExplorer.ts#L154) three lines below is in O(n²). The filtering should probably be done with a set, not an array. Generally, this entire "loop through all tests" for each folder and each item, [also seen in testNode.ts,](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/4d71f133951bc80e452ce8a9a842cae3e3a7b870/src/testNode.ts#L68) is really inefficient code.

**Comment by stefanforsberg** [comment]
@GeorchW I hear you but let's try to keep this thread about the original issue =)

When I execute this command `dotnet test --no-build --logger "trx;LogFileName=C:\SomePath\0.trx" --filter "FullyQualifiedName=XunitTests.TestClass3.Fail"` I end up with the following xml (the TestDefinition node)

```xml
<TestDefinitions>
    <UnitTest name="XunitTests.TestClass3.Fail(value: 2)" storage="d:\SomePath\vscode-dotnet-test-explorer\test\xunittests\bin\debug\netcoreapp3.1\xunittests.dll" id="5d23175e-8479-779f-39f4-23aa2608428b">
      <Execution id="ceaf151e-e91c-4f92-ba85-4af475de7c28" />
      <TestMethod codeBase="d:\SomePath\vscode-dotnet-test-explorer\test\xunittests\bin\Debug\netcoreapp3.1\XunitTests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="XunitTests.TestClass3" name="Fail" />
    </UnitTest>
  </TestDefinitions>
```

Since we are fetching the classname and method name from here it makes sense to me why the tree looks like it does but I don't really understand how it works for you. In order to rule out the possibility of different sdk versions containing different versions of vstest would you mind executing the above command in your context where things work and see if the resulting xml differ?

**Comment by GeorchW** [comment]
Sure, this is the part for me:
```xml
<TestDefinitions>
  <UnitTest name="XunitTests.TestClass3.Fail(value: 2)" storage="/path/to/the/repo/vscode-dotnet-test-explorer/test/xunittests/bin/debug/netcoreapp3.1/xunittests.dll" id="5d23175e-8479-779f-39f4-23aa2608428b">
    <Execution id="285b15ac-175b-4204-8d35-32dab901e73d" />
    <TestMethod codeBase="/path/to/the/repo/vscode-dotnet-test-explorer/test/xunittests/bin/Debug/netcoreapp3.1/XunitTests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="XunitTests.TestClass3" name="XunitTests.TestClass3.Fail(value: 2)" />
  </UnitTest>
</TestDefinitions>
```

Looks pretty similar to me...

**Comment by stefanforsberg** [comment]
Ah ok, then we need to figure out why the trx-files are different. I’ll continue investigating tomorrow :)

**Comment by stefanforsberg** [comment]
For me 
```
dotnet --version
3.1.300
```

**Comment by GeorchW** [comment]
Do you know whether there is a TRX spec somewhere? I wonder what the difference between the properties `UnitTest/@name` and `UnitTest/TestMethod/@name` is. Maybe we should really use the first one.

I'll try to have a look at the code of the TRX writer in the .NET SDK, but I generally think that we need to file an issue against the SDK.

**Comment by GeorchW** [comment]
I haven't found a specification and the code is a little hard to navigate. I've opened an issue there.

**Comment by stefanforsberg** [comment]
By the looks of their response we might do well to start looking at the UnitTest/@name field.

We might be able to use functionality to split a FQN into parts then right? I'm not sure at the top of my head what the implications for our implementation would be.

And as you are alluding to in #269 it's hard to know if this field will be stable going forward.

**Comment by GeorchW** [comment]
> We might be able to use functionality to split a FQN into parts then right?

[We already do, partially.](https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/2fee12ade29cbca08b6f6cbc42aa92b1fb8c30de/src/testResult.ts#L49)
