### ISSUE TITLE
Discover tests from *.sln included projects

### ISSUE THREAD

**Issue by evgeny-shkard-cyber** [formulahendry/vscode-dotnet-test-explorer#277]
Hi,
We have some test projects that is not included in .*sln file
Sims that dotnet-test-explorer.testProjectPath ignoring *.sln file refference and not resolving test projects included in solution.
Can this be achieved otherwise? (without renaming folders or csproj file)

**Comment by stefanforsberg** [comment]
I'm not sure I quite understand your problem but in general discovering and executing tests from a solution file does not work great (see comment on #265 for possible solution)

**Comment by evgeny-shkard-cyber** [comment]
The problem is that some test projects is not included in solution file and can not be excluded by current provided solution of (**/*Test*/*.csproj inclusion only).
If you'd provide abbility to also have exclusion pattern it may work.

**Comment by stefanforsberg** [comment]
I see, this is more or less the same issue as #276. Closing this and we'll continue the discussion in that issue.
