### ISSUE TITLE
The lens code is not displayed

### ISSUE THREAD

**Issue by ShadowManOldPS** [formulahendry/vscode-dotnet-test-explorer#278]
DotNet: 3.1.105

In the line of the lens code, the Start and Debug buttons are not displayed. My test project is in another project. The namespace is different, maybe because of this a problem. How to solve it?

![image](https://user-images.githubusercontent.com/30155360/87299200-407a5c00-c514-11ea-8b8d-efa295b59109.png)

![image](https://user-images.githubusercontent.com/30155360/87299458-bbdc0d80-c514-11ea-8cfa-27e89f9ae5ac.png)

![image](https://user-images.githubusercontent.com/30155360/87299890-8b48a380-c515-11ea-9970-0e8916ee5c35.png)

![image](https://user-images.githubusercontent.com/30155360/87300012-c054f600-c515-11ea-92f2-22e05862526b.png)

**Comment by stefanforsberg** [comment]
Hello! This extension only adds the result to the code lens (the red X in your images). The run/debug test buttons are from the c# extension

Hope that helps!
