### ISSUE TITLE
Failed to find tests with "Windows Display Language" different than English

### ISSUE THREAD

**Issue by andregiacomini** [formulahendry/vscode-dotnet-test-explorer#285]
1. Dotnet sdk version
.net Core 3.1.101

2. Unit test framework and relevants versions of that
Nunit

3. A link to a repo that replicated the issue

Not applicable,

Steps:
1. In windows 10+ change "Windows Display Language" in Language to any other than English.
2. Restart windows
3. In cmd/PS, verify responses to any command are NOT in English, but in the language setted in step 1
4. Try to update the test list in .net core test explorer in vscode

**Comment by stefanforsberg** [comment]
This is a known issue that's covered in the readme.
