### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PraveenADPP** [formulahendry/vscode-dotnet-test-explorer#287]
- Issue Type: `Bug`
- Extension Name: `dotnet-test-explorer`
- Extension Version: `0.7.4`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by stefanforsberg** [comment]
Hello and thanks for reporting. Unfortunately without the pasted data it's hard to do anything with this issue so I'm closing it. Feel free to open another one if you manage to recreate the error.
