### ISSUE TITLE
Tests are not discovered

### ISSUE THREAD

**Issue by TFTomSun** [formulahendry/vscode-dotnet-test-explorer#291]
I use 
vscode 1.51.1 
.NET Core Test Explorer 0.7.4 
TargetFramework:  netcoreapp3.1
NUnit 3.x

The projects are discovered, but no tests are shown. Here's the last part of the output:

> 
> Finding projects for pattern c:/git\appgates\core//**/*.Tests.csproj
> Found 1 matches for pattern in folder c:\git\appgates\core
> Evaluating match c:/git/appgates/core/src/AppGates.Net.Build.Dotnet.Tests/AppGates.Net.Build.Dotnet.Tests.csproj
> Adding directory c:/git/appgates/core/src/AppGates.Net.Build.Dotnet.Tests
> Executing dotnet test -t -v=q in c:/git/appgates/core/src/AppGates.Net.Build.Dotnet.Tests

If I execute the last command of the log in a shell it works fine, it finds my tests within that test project.

**Comment by jiveras** [comment]
I experience the exact same problems and I'm running same versions.

**Comment by buksy90** [comment]
I have same issue, running the command manually returns

```
The following Tests are available:
    DashboardDistanceLast5WeeksUrlAndParametersForAsset
    DashboardDistanceLast7DaysUrlAndParametersForDriver
    DashboardStatus_Driver_All
    ...
```

**Comment by mjnorman** [comment]
+1 for this issue.

**Comment by mjnorman** [comment]
For anyone finding this issue, I was attempting to troubleshoot the issue and ran the following steps.  After which my tests are now discovering and working.  I would imagine this is some fluke that it worked, but wanted to share in case it helps others:

- Ensure a global.json exists in the project (or parent project).  I realized I had .net5 sdk installed, so running dotnet test is going to run under the latest sdk unless you pin with a global.json
- Created a new test project with xunit (my existing project is nunit, so wanted to rule that out).  `dotnet new xunit -o MyTests`.  This new test project showed up correctly in the Test Explorer.
- Created a new test project with nunit (a new one, same project). `dotnet new nunit -o MyNunitTests`.  This new project did **not** show up in the Test Explorer
- I then removed both of the temp Test Project folders from disk completely
- After this I noticed that my original `dotnet test -t -v=q` was no longer listing my real tests.
- did a `dotnet clean` then `dotnet build` and then `dotnet test -t -v=q` was correctly showing my tests again
- Refreshed the view in the Test Explorer, and all tests are shown and working

**Comment by KieranSunshine** [comment]
I'm having this issue too. Added a global.json file as per @mjnorman suggestion but to no avail unfortunatley. Can also verify that creating a new nunit project will return 0 tests within the test explorer. However running `dotnet test -t -v=q` does correctly show my tests.

**Comment by janaka** [comment]
An update was released today. If you think your issues are still related to commands running with .NET5 worth a try. There was .NET5 related fix as I understand. Worth a try.

**Comment by KieranSunshine** [comment]
Awesome, updating to 0.7.5 seems to have done the trick for me. Thanks!

**Comment by andrewbusch7** [comment]
Working fine for me with v0.7.5 and .NET 3.1, thanks for the fix!
