### ISSUE TITLE
Add option to specify a solution

### ISSUE THREAD

**Issue by gldraphael** [formulahendry/vscode-dotnet-test-explorer#31]
Need an option to specify a solution when multiple solutions exist in the root directory.

In my specific instance, `dotnet test solution-name.sln` works fine, but there's no way to ask the test explorer to do something similar.

**Comment by janaka** [comment]
@stefanforsberg this should be a none issue now with the new multi solution support right?

**Comment by stefanforsberg** [comment]
This is not related to the mutiple projects support, if there are more than one solution file in a folder being used the dotnet cmds will not work.

**Comment by stefanforsberg** [comment]
But you should be able to use another newish setting called testArguments. If you set it to "solution-name.sln" it should work. Give it a try =)

**Comment by gldraphael** [comment]
Works like magic! Thanks!
