### ISSUE TITLE
Support for bUnit snapshot tests

### ISSUE THREAD

**Issue by dev-in-disguise** [formulahendry/vscode-dotnet-test-explorer#311]
Hi,

I'm currently working on a Blazor project which uses bUnit in combination with xUnit for testing the components. 
One feature of bUnit are so called snapshot tests which let you define a test input and expected output in a razor style syntax. For more infos on that you can have a look [here](https://github.com/egil/bUnit/blob/f0e030b9f15a4af54a0d897524e80a171ebd4442/src/bunit.web.testcomponents/README.md#creating-a-test-using-the-snapshottest-component) and [here](https://github.com/egil/bUnit/blob/f0e030b9f15a4af54a0d897524e80a171ebd4442/src/bunit.web.testcomponents/README.md#snapshottest-details).

Now on to the issue(s).

The _.net test explorer_ recognizes the snapshot tests, sets the correct name/description but places them outside of the project structure as something unrecognized:
![image](https://user-images.githubusercontent.com/16714208/115960778-981e0d00-a513-11eb-9e40-f16d87463d87.png)

Also running the snapshot tests via the _.net test explorer_ doesn't yield any result although running the via `dotnet test` manually works just fine. 

For the test run I already figured out the source of the issue. The `dotnet test` command that's triggered has a `--filter` option which takes the `Description` of the snapshot test as the _FullyQualifiedName_ and therefore can't find it. Is this something that could be fixed in the test explorer? I hope so since the Visual Studio test explorer recognizes and executes snapshot tests just fine. 

@egil could you potentially provide some insights into how the description of a snapshot test effects the test itself? 

My setup:

1. Dotnet sdk version: 5.0.103
2. Unit test framework and relevants versions of that: 
* xUnit 2.4.1
* bunit.web 1.0.0-preview-01
* bunit.xunit 1.0.0-preview-01
3. A link to a repo that replicated the issue: [F0.Minesweeper](https://github.com/Flash0ver/F0.Minesweeper). The snapshot tests can all be found in _F0.Minesweeper/source/test/F0.Minesweeper.Components.Tests/_. 

Thanks in advance for having a look at the issue!

**Comment by egil** [comment]
The description works the same as the DisplayName property of the fact attribute in regular xunit tests, i.e. `[Fact(DisplayName = "Foo Bar Baz")]`, so i dont think it is something you can filter on. Instead, filter on test components name.

Ps. In v1 of bUnit, I moved the snapshot feature into a separate library, and don't plan to do more development on it. It was an experimental solution, which I believe we now have a better solution for. See the release notes for details: https://github.com/bUnit-dev/bUnit/releases/tag/v1.0.16

**Comment by dev-in-disguise** [comment]
Thanks for clearing this up! 

Then I guess from my standpoint I'll move away from snapshot tests since they are now kind of deprecated and close this issue here.

**Comment by egil** [comment]
@dev-in-disguise sounds good. Let me know if you have any questions about the migration.
