### ISSUE TITLE
WSL2: Could not find test (no symbols found) 

### ISSUE THREAD

**Issue by MarkusRodler** [formulahendry/vscode-dotnet-test-explorer#313]
I can't open the tests from the Test Explorer. I made a dummy project:
`dotnet new mstest -n Test`
And set the project path:
`"dotnet-test-explorer.testProjectPath": "**/*Test.csproj"`

=> The project can be found and the test can be executed but not opened because of the error "Could not find test (no symbols found)"
I am using .NET 5.0.202, WSL 2 Debian and this is my project:
![image](https://user-images.githubusercontent.com/14873906/116850025-28cdaa80-abf0-11eb-8c8f-bd64cfef413e.png)

**Comment by MansMarius-Intenda** [comment]
Check this if you are on WSL or linux: https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/179
