### ISSUE TITLE
3 proposals to solve the pending "tooling language must be english" problem / requirement

### ISSUE THREAD

**Issue by Henry-Jones** [formulahendry/vscode-dotnet-test-explorer#315]
1. Check the known issues -> https://github.com/formulahendry/vscode-dotnet-test-explorer#known-issues
2. Check for other opened or closed issue matching yours?

see #77 , #96 , #107 and maybe others.

Deleting the relevant language folder solves this issue, but it seems to be a rather blunt measure.

a comment in #310 pointed me in the right direction. Obviously the problem stems from the regex in the function "extractAssemblyPaths" in the module / file testDiscoveries.ts. This is usually the first line after the call of the command:
 `dotnet test -t -v=q <foldername>`

One solution often mentioned is using the environment variable DOTNET_CLI_UI_LANGUAGE set to "en". This works only on all following lines, but the first line still stays in the current language of the system / powershell instance.

I also tried `[System.Threading.Thread]::CurrentThread.CurrentCulture = "en"` but this is ignored completely, obviously language settings are not inherited from the calling shell.

So I went with the regex. I changed the line from:
`const testRunLineRegex = /^Test run for (.+\.dll)/gm;`
to
`const testRunLineRegex = /^.*\"(.+\.dll)\"/gm;`

and it worked as far as I can check on my german set system. I build a test solution with all kind of tests (MSTest, NUnit, xUnit) and all are found succesfully.

If this regex is used elsewhere and needs to capture the part "Test run for" for other reasons, this change will probably break something else later on.

- So proposal 1 is to change this line, usually I would create a pull request, but I'm not familiar with TypeScript nor this project, so I'd rather not imposing something I cannot keep up with.

- In case this is needed as it is, proposal 2: create a list of strings, in the given languages. This might expand over time, but you could adapt the regex depending on the detected language of the environment.
 
- and no. 3: make a setting, where the user can enter this part "Test run for" from his language. This might be tricky as I was unable to get it to work in German, where it is called "Testlauf für" and I did not find the correct codepage to represent the "ä" umlaut.

**Comment by chausner** [comment]
Agree, it would be nice if this long-standing issue could be fixed/a workaround be implemented. The extension is currently completely broken on non-English systems and no error message or anything helpful is shown, so users may think something is wrong with their setup or project.

There has been a [PR](https://github.com/formulahendry/vscode-dotnet-test-explorer/pull/236) pending since Nov 2019 that adapts the regex as also @Henry-Jones suggests here, which seems like an acceptable workaround. Certainly better than the current state. :)

@formulahendry @janaka Any chance #236 could be merged or an equivalent fix be implemented?

**Comment by stefanforsberg** [comment]
Hello!
One of the underlying issues is that there may not be one regexp that works for all the language settings. For instance the proposed regexp would work for German (or indeed other languages where the CLI surrounds the assembly path with quotes) but it would not work for the output for Portuguese listed in this issue comment https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/77#issuecomment-390301958.

We can't realistically check the output for all the different CLI languages so I'm not sure what options we have besides allowing the user to set a regexp.

**Comment by chausner** [comment]
@stefanforsberg Thanks, I see. These are the localized strings for all languages that the SDK currently supports:

| language | format string      |
|---------|-----------------------------------|
| cs      | Testovací běh pro {0} ({1})       |
| de      | Testlauf für "{0}" ({1})        |
| en      | Test run for {0} ({1})            |
| es      | Serie de pruebas para {0} ({1})   |
| fr      | Série de tests pour {0} ({1})     |
| it      | Esecuzione dei test per {0} ({1}) |
| ja      | {0} ({1}) のテスト実行            |
| ko      | {0}({1})에 대한 테스트 실행       |
| pl      | Przebieg testu dla: {0} ({1})     |
| pt-BR   | Execução de teste para {0} ({1})  |
| ru      | Тестовый запуск для {0} ({1})     |
| tr      | {0} ({1}) için test çalıştırması  |
| zh-Hans | {0} ({1})的测试运行               |
| zh-Hant | {0} 的測試回合 ({1})              |

**Comment by stefanforsberg** [comment]
@chausner Thanks a bunch. Where did you find that list? If we were to add a setting for that it will come in handy to have a source in case they add/edit them.

**Comment by chausner** [comment]
The strings are contained as .NET resources in the Microsoft.TestPlatform.Build.resources.dll files in the SDK folder. You can view them with ILSpy, for example.

I think requiring users to set regexes in a setting would be a poor solution. While it would allow advanced users, who are willing to spend time reading and investigating the issue, to make the plugin work for any language, it is much too complicated for the majority of users.

Since it's only 14 languages, I think we could easily hardcode one regex for each language in the extension. In case new languages get added or format strings changed in the future, the extension might be broken for a small fraction of users until the extension is updated.

**Comment by stefanforsberg** [comment]
@chausner Agree with you regarding the regexp.

I've opened an issue on the vstest repo (since the underlying issue for the behavior feels like a bug in the dotnet test/vstest tooling) https://github.com/microsoft/vstest/issues/3029.

Let's wait a day or two and see what response we might get from that and see how we should move forward with this issue.

**Comment by nohwnd** [comment]
I agree that the message should be fixed, but (and please correct me if I am wrong), is this project relying on parsing the output? If so, you'd have much easier time either registering your own logger via the logging extension point, which would post the data back to VSCode via net pipes. Or using our interfacing layer to get the data programatically and posting that to your vscode via pipe. 

For the pipe stuff, (and also integrating with the new test UI in vscode) you can check out this repo, where Justin does this from a powershell instance for powershell tests (powershell is also .net so the communication code is similar except for few extra [] and ::). 

https://github.com/pester/vscode-adapter

https://github.com/pester/vscode-adapter/blob/4287a281f5d8d5830ec865af06f6f7aec9a69005/Scripts/PesterInterface.ps1

For programatic integration with vstest console you can use IVSTestConsoleWrapper, see for example how stryker integrates with it to run tests on the code it mutates:
https://github.com/stryker-mutator/stryker-net/blob/fff096f54c3cb469221b282b888a39d57a7e4bb5/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs#L95

**Comment by stefanforsberg** [comment]
@nohwnd Thank you for providing examples of a better implementation. We are aware of everything that's sub optimal about parsing the console output and there have been a few tries over the years implementing other alternatives more in line with what you are suggesting above. Let's just say that the number of people suggesting how we should do it is greater than working implementations in pull requests 😅

I really wish I had the time to look at and implement what you're suggesting but alas time is a resource I have too little of. But your examples should provide a very nice head start for someone with more time on their hands.

**Comment by nohwnd** [comment]
> Let's just say that the number of people suggesting how we should do it is greater than working implementations in pull requests 😅 

I know that feeling. Feel free to remind me in January to have another look at this. From a brief look, you would be able to benefit from the custom logger, without having a huge impact on the project architecture. The logger dll can be built against netstandard and added as an additional parameter to the test run.

**Comment by stefanforsberg** [comment]
@chausner Your PR (thanks a lot!) should be in the latest release of the extension 0.7.7. Would be lovely if you could give it a spin.

**Comment by Henry-Jones** [comment]
version 7.7.0 works with the language set to german. All three kinds of tests are found successfully. If I find the time I'll check some other languages on our multi language  test system and will report back.

Thanks to all.
