### ISSUE TITLE
Doesn't work with NET 5

### ISSUE THREAD

**Issue by Fosol** [formulahendry/vscode-dotnet-test-explorer#316]
I'm attempting to run and debug unit tests with a .NET 5.0 project.  I recently upgraded from 3.1.

I'm using Xunit for testing.

When I click on the "Run Test" it builds but doesn't run any test.

When I click on the "Debug Test" it builds but throws error "Failed to start debugger: System.InvalidOperationException: The debugger could not be started..."

**Comment by Henry-Jones** [comment]
What is the content of the "show log" window (button in the upper left corner of the test explorer) ?

**Comment by Fosol** [comment]
Sorry forgot I submitted this and didn't update.  After restarting VSCode it appears to work.  Not sure what steps made it work, but I did delete all the `/bin` and `/obj` folders too.  I suspect something was caching or using the wrong build.
