### ISSUE TITLE
Glob finds test.csproj, cannot run tests, error is "-"

### ISSUE THREAD

**Issue by brnwdrng** [formulahendry/vscode-dotnet-test-explorer#317]
What does the last line mean? There's supposed to be some explanation after v=q, but there's just a hyphen:

> Finding projects for pattern c:/TFS\ADO\Api.Message/**/*.Tests.csproj
Found 1 matches for pattern in folder c:\TFS\ADO\Api.Message
Evaluating match c:/TFS/ADO/Api.Message/Message.Tests/Message.Tests.csproj
Adding directory c:/TFS/ADO/Api.Message/Message.Tests
Executing dotnet test -t -v=q in c:/TFS/ADO/Api.Message/Message.Tests
[ERROR] Error while executing dotnet test -t -v=q - 

All of my unit tests pass, but the extension can't seem to pick them up.  My project structure is pretty typical, looks like this:

Api.Message
--- message.code-workspace
--- README.md
--- .vscode/
--- Message.Api/
--- --- Message.Api.csproj
--- --- ...
--- Message.Tests/
--- --- Message.Tests.csproj
--- --- UnitTests.cs

---
1. Dotnet sdk version 5.0.3 (also tried 5.0.2)
2. VS Code version 1.56.2
3. xUnit 2.4.1

**Comment by Henry-Jones** [comment]
what is the result when the command `dotnet test -t -v=q c:/TFS/ADO/Api.Message/Message.Tests` is run in a normal powershell console ?

**Comment by brnwdrng** [comment]
It returns a list of tests as expected; I found that other thread about localization, however: it was the (other then en) language directories existing in the dotnet sdk 5 directory.  Removing all of them except en/ fixed it immediately...
