### ISSUE TITLE
[Question] What is default pathForResultFile

### ISSUE THREAD

**Issue by lonix1** [formulahendry/vscode-dotnet-test-explorer#320]
Does someone know what is the default for `"dotnet-test-explorer.pathForResultFile"`?

I know I can set it manually, but I'm trying to figure out what the default is.

**Comment by stefanforsberg** [comment]
Hello! The default path is the temp directory for your OS. Exactly where that is varies depending on your OS but you can see where it tries to store the test file by clicking the log (after you've run at least one test)

![image](https://user-images.githubusercontent.com/358570/122816242-c2ebce00-d2d6-11eb-96c4-94736091fa61.png)

There you should see a line like this which should tell you were the result files are placed

![image](https://user-images.githubusercontent.com/358570/122816489-13632b80-d2d7-11eb-9312-945420063a58.png)

**Comment by lonix1** [comment]
Thanks!!!
