### ISSUE TITLE
The addProblems option is ignored

### ISSUE THREAD

**Issue by lonix1** [formulahendry/vscode-dotnet-test-explorer#321]
dotnet 5.0.300
vscode 1.57.0
extension 0.7.5
nunit 3.13.2

I set `"dotnet-test-explorer.addProblems": false` but errors are still shown in the problems view.

I fix the tests, and the problems disappear. I break the tests and the problems reappear. I think that setting is ignored.

**Comment by stefanforsberg** [comment]
Hey @lonix1. You might need to reload vscode after changing this setting for it to take effect.

**Comment by lonix1** [comment]
You are right, thank you.
