### ISSUE TITLE
Does not delete old tests from explorer

### ISSUE THREAD

**Issue by lonix1** [formulahendry/vscode-dotnet-test-explorer#324]
## Environment
dotnet: 5.0.301
vscode: 1.58.0
extension: 0.7.5

## This works
1. add a test
2. run tests in test explorer
3. new test is automatically added

## This doesn't work
1. delete a test
2. run tests in test explorer
3. old test is not deleted, it still shows

To fix this, I can refresh the test explorer (refresh button), and the old test disappears. But that refresh takes a long time on a large project.

**Comment by stefanforsberg** [comment]
Hello, I understand your pain point but  unfortunately there is no real good way to know if a test is removed outside  of a full test discovery.

**Comment by lonix1** [comment]
Yeah I guess that makes sense, now that I think of it!
