### ISSUE TITLE
Rootnamespace containing a . - Test sources can not be found

### ISSUE THREAD

**Issue by Bjego** [formulahendry/vscode-dotnet-test-explorer#334]
Hey,
I just spotted that my testsources aren't found as soon I add my Rootnamespace to the test file.
This test is resolved correctly:
```csharp
using Xunit;

  public class BjegosTest
  {
    [Fact]
    public void ThisIsOkay()
    {
      Assert.True(true);
    }
  }
```
and this one isn't:

```csharp
using Xunit;
namespace MyProject.Tests
{
  public class BjegosTest
  {
    [Fact]
    public void ThisIsOkay()
    {
      Assert.True(true);
    }
  }
}
```
By the way I've set the rootnamespace property in my csproj file as well.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>MyProject.Tests</RootNamespace>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyProject\MyProject.csproj" />
  </ItemGroup>
</Project>
```

**Comment by Bjego** [comment]
This happens also, if a namespace contains multiple dots in the name like: MyProject.Integration.Tests

**Comment by stefanforsberg** [comment]
Hello! This seems odd and should work unless I'm misunderstanding what you mean. Our internal xunit test-case has namespaces (with dots) and is working (https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/master/test/xunittests/TestClass1.cs).

Could you provides some more screenshots and/or logs and that might help explain what's happening.

**Comment by Bjego** [comment]
Hi, I'll collect them and give you an update.
Can I raise the loglevel somehow? Where do I find the most usefull logs?

**Comment by stefanforsberg** [comment]
The logs that would be interesting to see are available here: https://github.com/formulahendry/vscode-dotnet-test-explorer#logging

**Comment by Bjego** [comment]
Thanks.
In some other projects - I can't reproduce the issue. So I'm going to close this one for now.
Thanks. If I face such an issue again - I'll have a look into the logs.
