### ISSUE TITLE
Unable to  extract assembly paths for xunit on MacOS

### ISSUE THREAD

**Issue by thetpaingwynn** [formulahendry/vscode-dotnet-test-explorer#337]
When I run `dotnet test -t -v=q`, it output like below
```
Test run for /Users/.../bin/Debug/netcoreapp3.1/Server.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.1
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
...
```
In the `testDiscovery.ts`, it is looking for string like `Server.Tests.dll (.NETCoreApp,Version=v3.1)`.
But the output from `dotnet test`, for my case, is like `Server.Tests.dll(.NETCoreApp,Version=v3.1)`.
Without space between `.dll` and `(`.
https://github.com/formulahendry/vscode-dotnet-test-explorer/blob/0b996b0541e6f5c53de874bdd6c4c5c8fa173b18/src/testDiscovery.ts#L88

It must be because of dotnet version, I think.
- dotnet-sdk: 3.1.401
- Microsoft.NET.Test.Sdk: 16.6.1
- xunit: 2.3.1

**Comment by stefanforsberg** [comment]
Hello, the extract assembly path should only come into play for nunit and mstest 🤔 

Is you underlying problem that your tests are not discovered?

**Comment by thetpaingwynn** [comment]
Hi, my apologies. I did another debug and found out that my project have some console output. That mess up the output and `extractTestNames` could not extract test names. Since it is happening only for my particular solution, I will close this issues.
Thank you.
