### ISSUE TITLE
Add setting to hide .NET Test Explorer

### ISSUE THREAD

**Issue by phil-harmoniq** [formulahendry/vscode-dotnet-test-explorer#34]
I work on projects in other languages and have no need for the test explorer in such cases. I'd preferably like to have .NET Test Explorer disabled in my user settings and enable it in the workspaces where I need it.

Thanks for making this tool!

**Comment by stefanforsberg** [comment]
You can enable extensions by workspace by selecting the Extensions sidebar thing and then the cog wheel has an option to disable the extension. You then do the same for the workspaces where you want the extension to be active by selecting enable (workspace) from the cogwheel menu.

Incoming professional screenshot:
![image](https://user-images.githubusercontent.com/358570/38290911-ba58256e-37dd-11e8-862a-c3deef039540.png)
