### ISSUE TITLE
Use native VS Code Testing UI

### ISSUE THREAD

**Issue by tvardero** [formulahendry/vscode-dotnet-test-explorer#363]
So you can focus more on other things and bugs.
https://code.visualstudio.com/api/extension-guides/testing

**Comment by LiangZugeng** [comment]
@tvardero do you know any test adapters or controllers for C# currently available which works with native VS code testing UI?

**Comment by tvardero** [comment]
@LiangZugeng 
> @tvardero do you know any test adapters or controllers for C# currently available which works with native VS code testing UI?

Someone already tried to implement it for omnisharp. PR was not approved tho 😔

https://github.com/OmniSharp/omnisharp-vscode/pull/5054

**Comment by LiangZugeng** [comment]
@tvardero Thanks, right now .NET Testing Explorer is still the best choice, will keep an eye on the progress for [omnisharp-rolyn](https://github.com/OmniSharp/omnisharp-roslyn) to implement a test controller.

**Comment by tvardero** [comment]
closing as the project is not maintained 
also there is "C# dev kit" which has unit tests support and uses vscode ui.
