### ISSUE TITLE
I see nothing after installing this extension

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [formulahendry/vscode-dotnet-test-explorer#37]
VS Code latest release updated this week, on windows 10 64bit, .net core 2.0 xUnit test project genereted from cli tools.

After installing this extension and restarting vscode multiple times I see nothing anywhere in the UI that has changed.  

The docs don't explain **where** I should see the .net test explorer ui so I don't know what to expect,  I'm guessing from context it shows somewhere in the UI but as there is nothing different anywhere I look I guess it just doesn't work.

Is this meant for Linux only or something?

I will uninstall and maybe check again a few releases down the road.

**Comment by teamdynamiq** [comment]
It is not Linux only.

It should be located in the left hand side in the explorer part of vscode.

![image](https://user-images.githubusercontent.com/34121425/36592863-c5d8118e-1897-11e8-8058-81188bf3a352.png)

**Comment by WhatFreshHellIsThis** [comment]
Ahh...I see it now, thank you.  You might want to change the screenshot to the above.

By default that displays at the very bottom on the left unexpanded so it blends in very well and is hard to spot when you don't know where it's going to be.
