### ISSUE TITLE
Deprecate Repo

### ISSUE THREAD

**Issue by ChaseKnowlden** [formulahendry/vscode-dotnet-test-explorer#385]
According to 
https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/#test-your-projects-with-expanded-test-explorer-capabilities, CSharp Dev Kit includes a test explorer, and it is officially released by Microsoft.

**Comment by eduardomezencio** [comment]
This extension here is MIT licensed, while the C# Devkit extension is proprietary. You can hardly consider this new thing a replacement for dotnet-test-explorer (or [dotnet-test-explorer](https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/385) for that matter, that you're also apparently very intrested in archiving/deprecating for some reason). https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_is-c-dev-kit-open-source-why-not

**Comment by ChaseKnowlden** [comment]
That's ok.
