### ISSUE TITLE
No tests shown in tree

### ISSUE THREAD

**Issue by OliverCole** [formulahendry/vscode-dotnet-test-explorer#39]
I have set `dotnet-test-explorer.testProjectPath`. The test explorer window still says 
> Please open or set the test project and ensure your project compiles.

The project compiles, the Run All Tests button works (and discovers tests), and the output file is written to the specificd path.
The Refresh button doesn't seem to do anything.

**Comment by mmcintyre123** [comment]
I have the exact same problem.  I have the dotnet-test-explorer.testProjectPath set to the folder containing my csproj file and the Features folder which contains the tests.

**Comment by teamdynamiq** [comment]
Hmm, could you try to just open the test project folder directly (so that the testProjectPath is not needed) and give that a spin?.

(On a side note maybe it would be helpful to add a setting to the extension for writing some form of debug log file with internal errors.)

**Comment by AOne-T** [comment]
Same issue. "Run all tests" button tries to run as tests all projects in my workfolder (solution).
Also in my case I need a way to set the SolutionDir environment variable before building/running tests.

**Comment by TFTomSun** [comment]
I have the same issue. I try to run NUnit tests. .NET Core SDK 2.1.3 is installed. When i refresh the test explorer the following message is shown:

Testlauf f�r "D:\Git\Tooling\src\Siemens.MindSphere.Nfr.Tests\bin\Debug\netcoreapp2.1\Siemens.MindSphere.Nfr.Tests.dll" (.NETCoreApp,Version=v2.1)
Microsoft (R) Testausf�hrungs-Befehlszeilentool Version 15.7.0
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

> Die folgenden Tests sind verf�gbar:
>     FirstContactNfrTest
>     OpenFlowCreatorTest
>     FirstContactNfrTest
>     OpenFlowCreatorTest
>     FirstContactNfrTest
>     OpenFlowCreatorTest
>     FirstContactNfrTest
>     OpenFlowCreatorTest
> 
>     at executeDotnetTest.then (C:\Users\adfrth5\.vscode\extensions\formulahendry.dotnet-test-explorer-0.4.0\out\src\testDiscovery.js:17:19)
>     at <anonymous>:null:null

**Comment by stefanforsberg** [comment]
@TFTomSun This is probably related to running dotnet tooling in a non english language, have a look at #77 for a "solution"

**Comment by bmccord** [comment]
I just found the cause for it happening on my machine.  I had a "Path For Result File" set, but the specified folder didn't exist on one of my projects.  That caused the "Discovering Tests" to just spin forever.  I took out the Path, restarted, and tests were found quickly.

**Comment by AboubakarAhamada** [comment]
> @stefanforsberg Thanks for the hint. The workaround solved the issue for me.
> 
> For everybody who come across this thread:
> 
> * Go to C:\Program Files\dotnet\sdk<sdkVersion>
> * move all language folders (e.g. cs, de, en, es, ... zh-*) to a subfolder
> * Start Visual Studio code
> * Refresh the test explorer -> the tests are shown now

After two weeks stucking on this issue, this finaly worked for me. Thanks

**Comment by dotnetdew** [comment]
> > @stefanforsberg Thanks for the hint. The workaround solved the issue for me.
> > For everybody who come across this thread:
> > 
> > * Go to C:\Program Files\dotnet\sdk
> > * move all language folders (e.g. cs, de, en, es, ... zh-*) to a subfolder
> > * Start Visual Studio code
> > * Refresh the test explorer -> the tests are shown now
> 
> After two weeks stucking on this issue, this finaly worked for me. Thanks

that is not worked
