### ISSUE TITLE
Setting for test result file name

### ISSUE THREAD

**Issue by damirarh** [formulahendry/vscode-dotnet-test-explorer#46]
I'm having problems changing the path for test results using the `dotnet-test-explorer.pathForResultFile` setting. As soon as I set any value for it in the workspace `settings.json` file (even just `.`), I can't run the tests from the .NET Test Explorer any more - nothing happens when I click _Run Test_ from the context menu. (I need to restart VS Code for the extension to pick up the new value. Until I do that it just uses the default path.)

Additionally, I'm wondering if it's supported to put a fixed filename in this setting. I would really like the results file to be fixed so that I could use dotnet watch to continuously run the tests and have the results appear in CodeLens and the Test Explorer panel, e.g.

```
dotnet watch test --logger "trx;LogFileName=.\testresults\Results.trx"
``` 

I could then put this command into my `tasks.json` file. Is this possible?

**Comment by stefanforsberg** [comment]
The part about pathForResultFile not changing until a restart should be doable.

About the other part I'll get back to you, but it sounds like a nice feature!
