### ISSUE TITLE
Support for runsettings

### ISSUE THREAD

**Issue by SchneiderPatrick** [formulahendry/vscode-dotnet-test-explorer#57]
Hey :)

Is there a way to include a runsettings file?

Greets

**Comment by stefanforsberg** [comment]
https://github.com/Microsoft/vstest-docs/blob/master/docs/RunSettingsArguments.md

**Comment by SchneiderPatrick** [comment]
I would like to implement this feature by myself and make a pull request. 
But I am not able to discover any tests when I´m trying to debug / test it.
This does not even work when I´m trying to run your extension without my changes.
Do you have an idea why I am facing this issue?

**Comment by teamdynamiq** [comment]
Basically you should be able to do the following

1. Clone the repo
2. npm install (in the folder you cloned the repo to)
3. Press F5 to start the application in debug mode

What error do you get?

**Comment by SchneiderPatrick** [comment]
The new option to pass additional arguments helps a lot.
Nice work!

**Comment by stefanforsberg** [comment]
Thanks! =)
