### ISSUE TITLE
Feature: Live unit testing

### ISSUE THREAD

**Issue by mustakimali** [formulahendry/vscode-dotnet-test-explorer#60]
Upon save, running the test method being edited (and update the test indicator) would be a useful feature.

**Comment by stefanforsberg** [comment]
Hey, 0.3.1 was just released which contains a setting called autoWatch. If you set that to true the extension should start watching after test discovery is completed. Give that a spin and please come back with feedback =)

I realize it's not exactly what you're asking for here but perhaps it's a good enough start?

**Comment by mustakimali** [comment]
Well done! That's a great start 😄 

As it leverages `dotnet watch` command, this requires a project path to be supplied or be run from within a test project's folder. So upon discovery, the issued command `dotnet watch run` throws this error

![image](https://user-images.githubusercontent.com/1546896/41355962-90c90096-6f1a-11e8-9b42-744fcf91948b.png)

When I `cd` into a specific test project's folder (as you can see in the screenshot above), it works. Also `dotnet watch` is little slow when you are just editing one single unit test but this is a good start and I am sure you will figure something out.

**Comment by stefanforsberg** [comment]
Cheers! <3

There is a setting called testProjectPath that you can set your test project path to to avoid this error. In your case I think test/ICA.test would do it.
