### ISSUE TITLE
Feature: Code Coverage

### ISSUE THREAD

**Issue by chuck-flowers** [formulahendry/vscode-dotnet-test-explorer#7]
It would be awesome to be able to determine what parts of a project are not being covered by tests. I'm not sure what the easiest way to do it in the extension is (and I know this is a difficult feature to add) but it's a feature that I've been looking for that is normally only available as a paid tool. Would love to have a discussion about how it could work given VS Code's current API surface.

**Comment by janaka** [comment]
@chuck-flowers so IMO coverage should be implemented as a separate extension. 

Here are two tools I've come across recently for .NET Core. Not sure if they all run on MacOS. OpenCover doesn't yet but works on Windows. I don't think any are VS Code extensions though. 
https://github.com/tonerdo/coverlet/ 
https://github.com/SteveGilham/altcover

**Comment by chuck-flowers** [comment]
Yeah I found out about coverlet a while after posting this and I've been meaning to check it out.

**Comment by janaka** [comment]
Cool. Going to close based on that.
