### ISSUE TITLE
Run test assumes tests are in the current terminal directory

### ISSUE THREAD

**Issue by rhyswat** [formulahendry/vscode-dotnet-test-explorer#8]
Hi folks,

This extension is very useful, so thank you :+1: 

However... the test directory does not appear to be evaluated prior to running a test. Tests are discovered correctly on refresh however.

environment:

- test explorer v 0.0.3
- VS Code Version 1.15.1
- Ubuntu 16.04
- Node 6.11.2

when:

- my VS Code terminal directory is *not* in a test directory
- I do *not* have my test .csproj open and in focus
- my .vscode/settings.json has `"dotnet-test-explorer.testProjectPath": "test/Integration"` (this is sane, otherwise refresh wouldn't list my tests)
- right-click on a test & run it

then:

- I get `Couldn't find a project to run test from. Ensure a project exists in <wherever>`

I think the issue might be in DotnetTestExplorer.runTest

How about re-evaluating (or computing on the fly) `this.cwd` as happens on refreshing the list of tests?

```js
const testProjectPath = Utility.getConfiguration().get<string>("testProjectPath");
let testProjectFullPath = testProjectPath ? testProjectPath : vscode.workspace.rootPath;
if (!path.isAbsolute(testProjectFullPath)) {
  testProjectFullPath = path.resolve(vscode.workspace.rootPath, testProjectPath);
}
this.cwd  = testProjectFullPath;
````

The test runs if I'm *already* in the test directory and there is a test csproj in "`.`"

Thanks,
Rhys

**Comment by rhyswat** [comment]
I have a local change but don't have write access to this repo to offer you a PR.

**Comment by formulahendry** [comment]
Hi @rhyswat , if you restart the VS Code, will the tests run normally?

**Comment by colin-young** [comment]
@rhyswat There are some good general guides on creating PRs from your forked copy. Here are a couple:

[Official GitHub](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)
[General overview/steps to Fork + PR](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

**Comment by rhyswat** [comment]
Hi @formulahendry -- immediately on opening VSCode and letting it scan for tests, the tests will run first time on hitting the play button in the .NET Tests Explorer extension. 

Looking at it a bit more, the test extension creates its own terminal initialised in my tests directory. Thus `dotnet test <options>` works as expected since there is a csproj in that directory for it to use.

However if I `cd somewhere-else` in the *extension's* terminal the tests no longer run. What is not obvious (to me) is that it's a separate terminal instance.

So it might be the case that a code solution is not required, but rather a bit of Readme documentation to point out that users like me should leave the extension's terminal alone ;-)

**Comment by rhyswat** [comment]
@colin-young thanks, noted.

**Comment by formulahendry** [comment]
New release has been published.
