### ISSUE TITLE
Run test(s) without build/restore context menu option

### ISSUE THREAD

**Issue by nn-afly** [formulahendry/vscode-dotnet-test-explorer#81]
Any interest in a PR that will deliver this? It would of been quite a time saver for me these last few days. Changing prefs a bit of a long winded alternative

![context menu addition](https://photos-1.dropbox.com/t/2/AAC4MPQnJB-I6J5dUvrMu4fLaABnhWnAlJXnoQef6Cf-oQ/12/102514326/png/32x32/3/1527087600/0/2/Screenshot%202018-05-23%2011.10.20.png/EOX8s08YhrijASACKAI/oIANUPFReTf9vGbiYyZokBwLJF8S-ccqWw7hQOc3H8k?dl=0&preserve_transparency=1&size=2048x1536&size_mode=3)

I made [a brief start](https://github.com/nn-afly/vscode-dotnet-test-explorer/tree/feature/no-build)  which works well but would likely wait for a #75 merge before putting together a PR

**Comment by guylando** [comment]
+1
