### ISSUE TITLE
FEATURE: Support for multiple test projects

### ISSUE THREAD

**Issue by shahabganji** [formulahendry/vscode-dotnet-test-explorer#86]
In an enterprise application, the system may be break into several sub-projects which will lead us to have multiple test projects representing unit tests of their corresponding main project. Currently the settings do not get multiple projects in here : 

```json
{
    "dotnet-test-explorer.testProjectPath": "./test/MyFirstTest"
}
```

It would be better if we can provide a master folder like ```"./test/"``` or even better to accept an array of paths 

```json
{
    "dotnet-test-explorer.testProjectPath": ["./test/MyFirstTest" , "./test/MySecondTest" ]
}
```

Thanks in advance :pray:

**Comment by stefanforsberg** [comment]
Hey, please have a look at #18 =)
