### ISSUE TITLE
Support for Xunit Theory with ClassData

### ISSUE THREAD

**Issue by mainedufresne** [formulahendry/vscode-dotnet-test-explorer#87]
I recently converted a project from nunit to xunit and in doing so had to implement my own TestCaseProvider, and Discoverer. This worked well enough but the explorer didn't allow me to run individual tests. The reason being that the command generated by the explorer was in the form `dotnet test --logger "trx;LogFileName=some/path/logfile.log" --filter FullyQualifiedName~Some.Namespace.TestCase` 

The discoverer I wrote displayed tests as "TestCase(testCaseParameters: <TestCaseName>)" testCaseParameters is another class I wrote to support my conversion from nunit but I do not think it plays much of a role here other than to be printed in the display name. 

After looking at the code I see in testCommand.ts the following:
    
    private runTestCommand(testName: string): void {
        let command = `dotnet test${this.getDotNetTestOptions()}${this.outputTestResults()}`;
    
        if (testName && testName.length) {
            command = command + ` --filter FullyQualifiedName~${testName.replace(/\(.*\)/g, "")}`;
        }

I can fix my own issue of running individual tests pretty simply by changing the above to the following:

    private runTestCommand(testName: string): void {
        let command = `dotnet test${this.getDotNetTestOptions()}${this.outputTestResults()}`;

        if (testName && testName.length) {
            command = command + ` --filter "FullyQualifiedName~${testName.replace(/\(.*\)/g, "")}`;
            let parenIdx = testName.indexOf("(");
            if(parenIdx >= 0 )
            {
                let closeParenIdx = testName.indexOf(")");
                let displayName = testName.substring(parenIdx+1, closeParenIdx);
                command = command + `&DisplayName~` + displayName;
            }
            command = command + `"`;
        }

This does successfully generate a command in the format `dotnet test --logger "trx;LogFileName=some/path/logfile.log" --filter "FullyQualifiedName~Some.Namespace.TestCase&DisplayName~(testCaseParameters: testCase1)"` and that does run the individual test. However, the implications of such a change are not clear to me. I think this would only want to happen if the test framework is XUnit but I am uncertain how/if I can determine that. Rather than open a half-baked PR, I thought it would be better to start a discussion on the issue.

**Comment by stefanforsberg** [comment]
Hey @mainedufresne. This has been up before and we've opted against it since DisplayName is only supported by xunit and we want to avoid unit test framework specific code if possible.

**Comment by mainedufresne** [comment]
Ah, okay. I understand. If I find another way to achieve the same goal without DisplayName I will let you know.

**Comment by teamdynamiq** [comment]
If you want to you can quite easily build your own version by doing the code modifications above and then

(update the version number in package.json if you want to)
npm install -g vsce
vsce package

This will give you a vsix-file that you can install in vscode if you go to the extensions and choose install from vsix in the ...-menu
