### ISSUE TITLE
Passing additional arguments to dotnet test

### ISSUE THREAD

**Issue by Oduig** [formulahendry/vscode-dotnet-test-explorer#93]
Is it possible to pass additional options to the dotnet test command, when running via the .NET test explorer? If not, would it be difficult to add a setting?

E.g. `dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov`

We want this feature so that we can generate a coverage file from https://github.com/tonerdo/coverlet/ so that it can be picked up by https://github.com/ryanluker/vscode-coverage-gutters .

**Comment by teamdynamiq** [comment]
Hey, at the moment we have settings for providing the test command with no-build and no-restore functionality. We're thinking about removing those as settings and add a new type of "additional args" setting where you can specify whatever args you want added. That we we can support the coverage and also #57 (for instance) and whatever else settings people need to feed to the test command without us actually having to add settings and / or code for it.

Sounds reasonable?

**Comment by Oduig** [comment]
@teamdynamiq That sounds perfect!

**Comment by equiman** [comment]
That sounds good. Maybe could be something like current task configuration:

```
{
            "label": "test",
            "command": "dotnet",
            "type": "process",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "args": [
                "test",
                "${workspaceFolder}/Project.Tests/Project.Tests.csproj",
                "/p:CollectCoverage=true",
                "/p:CoverletOutputFormat=\"opencover,lcov\"",
                "/p:CoverletOutput=../lcov"
            ],
            "problemMatcher": "$msCompile"
        },
```

... and thanks for your effort!!

**Comment by janaka** [comment]
So as it goes with do have a setting called `dotnet-test-explorer.testArguments` which appends to the `dotnet test` and `dotnet watch test` commands. 

I've done a quick test with Coverlet. It works. Note that Coverlet only seems to run when all tests in the run scope passes.

**Comment by janaka** [comment]
The quick test I did was by running source in debug mode. It would appear this is yet to be released. published extension 0.3.1 doesn't appear to have it. 

@teamdynamiq Looks like you added it 17days ago. https://github.com/formulahendry/vscode-dotnet-test-explorer/commit/338b03696ada7c2d356d11573e5d2d633494584d. I updated the README on master so we don't forget when you release.

**Comment by janaka** [comment]
Arg, should have looked at the release notes wiki. Sorry.

**Comment by janaka** [comment]
@Oduig BTW looks like there some coverage functionality being built into the VSTest platform (essentially what `dotnet test` is wrapping. However, it doesn't seem to be well documented. I've only seen references like this https://github.com/Microsoft/vstest/issues/1650

**Comment by janaka** [comment]
In addition to enabling general args, when they release code coverage into `dotnet` CLI on both Windows and Linux we should consider adding this as a special option. Something like `dotnet-test-explorer.generateCodeCoverage=[true[default]|false]`
 
https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0021-CodeCoverageForNetCore.md

**Comment by stefanforsberg** [comment]
Should be fixed with dotnet-test-explorer.testArguments, give it a spin =)

**Comment by equiman** [comment]
I have added this on workspace settings:
```json
{
    "dotnet-test-explorer.testArguments": "/p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov\" /p:CoverletOutput=../lcov",
}
```

When hit play on run all test show this error:

```bash
For switch syntax, type "MSBuild /help"
$ cd "/Users/jcmartinez/Developer/DEIN/Projects/_devTB"
$ dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat="opencover,lcov" /p:CoverletOutput=../lcov --logger "trx;LogFileName=/var/folders/t2/4y3bmxv15ks9lm42kwl51g_j88lrdf/T/test-explorer-WCpxrh/Results.trx"
MSBUILD : error MSB1006: Property is not valid.
Switch: lcov
```

But if I run the same as task, works fine:

```json
{
            "label": "test",
            "command": "dotnet",
            "type": "process",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "args": [
                "test",
                "${workspaceFolder}/ToolBox.Tests/ToolBox.Tests.csproj",
                "/p:CollectCoverage=true",
                "/p:CoverletOutputFormat=\"opencover,lcov\"",
                "/p:CoverletOutput=../lcov"
            ],
            "problemMatcher": "$msCompile"
        },
```
