### ISSUE TITLE
After the successful execution of the test also the test is spinning 

### ISSUE THREAD

**Issue by vinaysimharaju** [formulahendry/vscode-dotnet-test-explorer#98]
Hi,
I have created the dotnet core mstest project in Visual Studio code and .Net test explorer.
1) NUnit 
2) Selenium Web driver
Questions:
1) When I run the test, either by dotnet run or from explorer after the successful execution also the test is always spinning. 
2) I want to change the path of the result file storage how can I do it?

Kindly help me in finding the solution.

**Comment by teamdynamiq** [comment]
Have a look [here](https://github.com/formulahendry/vscode-dotnet-test-explorer#test-result-is-not-shown-in-codelens--tree) and see if that resolves the issue.
